### ISSUE TITLE
Acl check should not failed when a variable which is not related to the current state is set.

### ISSUE THREAD

**Issue by FanchTheSystem** [ansible-collections/ansible.posix#104]
##### SUMMARY

Acl check should not failed when a variable which is not related to the current state is set.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

acl

##### ANSIBLE VERSION

```paste below
ansible 2.10.2

  python version = 3.8.6 (default, Sep 30 2020, 04:00:38) [GCC 10.2.0]

```

##### CONFIGURATION

```paste below
NA
```

##### OS / ENVIRONMENT

Archlinux

##### STEPS TO REPRODUCE

```yaml
- name: Set ACL permission
  acl:
    path: "{{ acl_path }}"
    entity: "{{ acl_group }}"
    etype: group
    permissions: "{{ acl_group_perm }}"
    recursive: true
    state: "{{ acl_state }}"
```

with those vars:
```yaml
act_path: /my_path
acl_group: my_group
acl_perm: 'rwx'
acl_state: absent
```

##### EXPECTED RESULTS

It should remove the acl, as we set the state to 'absent'.

##### ACTUAL RESULTS

It failed with the error message:
```
'permissions' MUST NOT be set when 'state=absent'
```

The check is here in the source code:
https://github.com/ansible-collections/ansible.posix/blob/main/plugins/modules/acl.py#L305-L307

And we can read few line later that the permission variable is not used when the state is absent:
https://github.com/ansible-collections/ansible.posix/blob/main/plugins/modules/acl.py#L351-L361

My first point is that it should not failed, because the permission variable has no impact on the executed code when the state is absent. So the check protection is useless, It is not used to secure the code execution.
So I think it may be a warning ( maybe for best practice ) but it should not failed.

My second point which I think is also an issue, is that if you want to use a variable to set the state of the acl, then you must duplicate your code, something like:

```
- name: Set ACL permission
  acl:
    path: "{{ acl_path }}"
    entity: "{{ acl_group }}"
    etype: group
    permissions: "{{ acl_group_perm }}"
    recursive: true
    state: "{{ acl_state }}"
  when: acl_state != "absent"

- name: Set ACL permission
  acl:
    path: "{{ acl_path }}"
    entity: "{{ acl_group }}"
    etype: group
    recursive: true
    state: "{{ acl_state }}"
  when: acl_state == "absent"
```

And as you know, duplicate code for long term maintenance is never a good idea.
