### ISSUE TITLE
sysctl custom file permissions

### ISSUE THREAD

**Issue by mhalano** [ansible-collections/ansible.posix#108]
##### SUMMARY
 I save my custom configurations under /etc/sysctl.d/10-performance.conf (performance configs). The problem is when this file is created it has a very restrictive permission, 0600 to be exactly. Should be 0644 as the other files.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
sysctl

##### ANSIBLE VERSION

```paste below
ansible 2.10.0
  config file = /home/mhalano/projs/infra-marcos-new/ansible.cfg
  configured module search path = ['/home/mhalano/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0]

```

##### CONFIGURATION

```paste below
INTERPRETER_PYTHON(/home/mhalano/projs/infra-marcos-new/ansible.cfg) = auto
```

##### OS / ENVIRONMENT

Ubuntu 20.10 but using the ansible-base package from Eoan on the official repository.

##### STEPS TO REPRODUCE
.1 Execute this minimum tasks:

```yaml
- name: Reduce Swappiness
  sysctl:
    name: vm.swappiness
    value: "10"
    reload: yes
    state: present
    sysctl_file: /etc/sysctl.d/10-performance.conf
```
##### EXPECTED RESULTS

The file /etc/sysctl.d/10-performance.conf should have as permission 0644.

##### ACTUAL RESULTS

The file /etc/sysctl.d/10-performance.conf has permission 0600 even if it is not a critical file (security key or whereveer)

```paste below
mhalano@glados:~/projs/infra-marcos-new$ ls -lh /etc/sysctl.d/10-performance.conf 
-rw------- 1 root root 42 out 30 16:34 /etc/sysctl.d/10-performance.conf
```
