### ISSUE TITLE
firewalld module ignores value for masquerade attribute

### ISSUE THREAD

**Issue by kkeane** [ansible-collections/ansible.posix#116]
##### SUMMARY
The documentation for the firewalld module says that the masquerading attribute is of type string, but does not explain what the value of the string should be. The example code suggests that it should be "yes" or "no".

But regardless of what I set the value to, masquerading is always enabled. Looking at the source code for the firewalld module, it looks like the value for the masquerade attribute is completely ignored.

It is not clear if this is a bug in the behavior of the masquerade attribute, or a documentation issue, or probably both.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
firewalld module.

##### ANSIBLE VERSION

```
ansible 2.9.15
  config file = /home/kkeane/Documents/dev/ansible/ansible.cfg
  configured module search path = [u'/home/kkeane/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug 13 2020, 02:51:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
ANSIBLE_PIPELINING(/home/kkeane/Documents/dev/ansible/ansible.cfg) = True
DEFAULT_FORCE_HANDLERS(/home/kkeane/Documents/dev/ansible/ansible.cfg) = True
DEFAULT_FORKS(/home/kkeane/Documents/dev/ansible/ansible.cfg) = 30
DEFAULT_HOST_LIST(/home/kkeane/Documents/dev/ansible/ansible.cfg) = [u'/home/kkeane/Documents/dev/ansible/inventory/linux.yaml']
DEFAULT_MANAGED_STR(/home/kkeane/Documents/dev/ansible/ansible.cfg) = This file is managed by Ansible.%n
Do not edit this file. Changes will be reverted.%n
template: {file}
user: {uid}
host: {host}
DEFAULT_PRIVATE_KEY_FILE(/home/kkeane/Documents/dev/ansible/ansible.cfg) = <redacted>
DEFAULT_REMOTE_USER(/home/kkeane/Documents/dev/ansible/ansible.cfg) = svc-ansible
DEFAULT_ROLES_PATH(/home/kkeane/Documents/dev/ansible/ansible.cfg) = [u'/home/kkeane/Documents/dev/ansible/roles', u'/home/kkeane/Documents/dev/ansible/download-roles', u'/usr/share/ansible/roles
DEFAULT_TIMEOUT(/home/kkeane/Documents/dev/ansible/ansible.cfg) = 300
DEFAULT_VAULT_PASSWORD_FILE(/home/kkeane/Documents/dev/ansible/ansible.cfg) = /home/kkeane/Documents/dev/ansible/vault-passwords
DISPLAY_SKIPPED_HOSTS(/home/kkeane/Documents/dev/ansible/ansible.cfg) = False
INVENTORY_ENABLED(/home/kkeane/Documents/dev/ansible/ansible.cfg) = [u'yaml', u'script', u'ini']
```

##### OS / ENVIRONMENT
Target device runs RedHat Enterprise Linux 8.3. The problem probably occurs in all versions.

##### STEPS TO REPRODUCE
Run the following first of the tasks listed below.

Then verify whether /etc/firewalld/zones/testzone.xml contains the tag.

The run the second of the tasks listed below.

Again verify whether /etc/firewalld/zones/testzone.xml contains the tag.

```yaml
        - name: Testing enabling masquerading (this works)
          ansible.posix.firewalld:
            zone:      'testzone'
            masquerade: yes
            permanent:  yes
            state:      enabled
            offline:    True

        - name: Testing disabling masquerading (this fails)
          ansible.posix.firewalld:
            zone:      'testzone'
            masquerade: no
            permanent:  yes
            state:      enabled
            offline:    True
```
To verify results, use either of the following two commands:

```
    cat /etc/firewalld/zones/testzone.xml
    grep masquerade /etc/firewalld/zones/testzone.xml
```

##### EXPECTED RESULTS
After first test case:
Expected result: testzone.xml contains a tag.

After second test case:
Expected result: testzone.xml does not contain a tag.

##### ACTUAL RESULTS
For both test cases:
Actual result: testzone.xml contains a tag.

This is correct for the first test case, incorrect for the second test case.
