### ISSUE TITLE
mount module reset the ownership & group ownership to root:root

### ISSUE THREAD

**Issue by Udayendu** [ansible-collections/ansible.posix#127]
##### SUMMARY
**mount** module is resetting the ownership of the mount directly which was created jus in the above play using **file** module.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- mount

##### ANSIBLE VERSION
```
$ pip3 show ansible
Name: ansible
Version: 2.10.4
Summary: Radically simple IT automation
Home-page: https://ansible.com/
Author: Ansible, Inc.
Author-email: info@ansible.com
License: GPLv3+
Location: /usr/local/lib/python3.6/site-packages
Requires: ansible-base

$ pip3 show ansible-base
Name: ansible-base
Version: 2.10.4
Summary: Radically simple IT automation
Home-page: https://ansible.com/
Author: Ansible, Inc.
Author-email: info@ansible.com
License: GPLv3+
Location: /usr/local/lib/python3.6/site-packages
Requires: jinja2, PyYAML, cryptography, packaging
```

##### OS / ENVIRONMENT
- Provision Server: CentOS 8.3
- Target systems: OEL 8.3

##### STEPS TO REPRODUCE
- Create a directly and try to change the ownership/group ownership using file module
- It will create the directory and will change the ownership/group ownership
- Then perform the mount operation and ownership/group ownership are back to root:root

```
---
- name: Service user creation
  user:
    name: "{{ item }}"
    state: present
  with_items:
    - jboss
    - appdev
    - appmonitor

- name: appvg volume group creation
  lvg:
    vg: appvg
    pvs: '{{ disk_name }}'

- name: applv00 lvm creation
  lvol:
    vg: appvg
    lv: applv00
    size: 100%FREE

- name: Create a filesystem for applv00
  filesystem:
    fstype: xfs
    dev: /dev/appvg/applv00

- name: Create mount point "{{ appmount_point }}"
  file:
    path: "{{ appmount_point }}"
    state: directory
    recurse: yes
    owner: jboss
    group: jboss
    mode: '0755'

- name: Mount applv00 logical volume under '{{ appmount_point }}'
  mount:
    name: '{{ appmount_point }}'
    src: /dev/appvg/applv00
    fstype: xfs
    state: mounted
```

##### EXPECTED RESULTS
- Permission of the mount point should be intact as set by the file module

##### ACTUAL RESULTS
- Permission of the mount point is set back to root:root
- But if try to adjust the mount point permission change after mount, it worked well using the below code:

```
---
- name: Service user creation
  user:
    name: "{{ item }}"
    state: present
  with_items:
    - jboss
    - appdev
    - appmonitor

- name: appvg volume group creation
  lvg:
    vg: appvg
    pvs: '{{ disk_name }}'

- name: applv00 lvm creation
  lvol:
    vg: appvg
    lv: applv00
    size: 100%FREE

- name: Create a filesystem for applv00
  filesystem:
    fstype: xfs
    dev: /dev/appvg/applv00

- name: Create mount point "{{ appmount_point }}"
  file:
    path: "{{ appmount_point }}"
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: '0755'

- name: Mount applv00 logical volume under '{{ appmount_point }}'
  mount:
    name: '{{ appmount_point }}'
    src: /dev/appvg/applv00
    fstype: xfs
    state: mounted

- name: Change the permission of '{{ appmount_point }}' directory
  file:
    path: "{{ appmount_point }}"
    state: directory
    recurse: yes
    owner: jboss
    group: jboss
    mode: '0755'
```

I have seen this bug https://github.com/ansible/ansible/issues/58916 but in my case its a local mount.
