### ISSUE TITLE
Can't mount davfs2 mount point

### ISSUE THREAD

**Issue by Fatsie** [ansible-collections/ansible.posix#136]
##### SUMMARY
Can't mount davfs remote webdav site with mount module.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible-posix.mount_module

##### ANSIBLE VERSION
```paste below
ansible 2.10.5
  config file = /home/verhaegs/workspace/infra_setup/ansible/ansible.cfg
  configured module search path = ['/home/verhaegs/.ansible/collections/ansible_collections/debops/debops/plugins/modules']
  ansible python module location = /home/verhaegs/software/python/debops/lib/python3.8/site-packages/ansible
  executable location = /home/verhaegs/software/python/debops/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### CONFIGURATION
```paste below
DEFAULT_HOST_LIST(/home/verhaegs/workspace/infra_setup/ansible/ansible.cfg) = ['/home/verhaegs/workspace/infra_setup/ansible/inventory/hosts']
DEFAULT_LOOKUP_PLUGIN_PATH(/home/verhaegs/workspace/infra_setup/ansible/ansible.cfg) = ['/home/verhaegs/.ansible/collections/ansible_collections/debops/debops/roles/ansible_plugins/lookup_plugins']
DEFAULT_MODULE_PATH(/home/verhaegs/workspace/infra_setup/ansible/ansible.cfg) = ['/home/verhaegs/.ansible/collections/ansible_collections/debops/debops/plugins/modules']
```

##### OS / ENVIRONMENT

controller: Linux Mint 20
target: Debian 10

##### STEPS TO REPRODUCE

Example playbook (changed URL to example.com):
```yaml
- name: davfs on dl580
  hosts: [ dl580 ]
  tags: [ 'role::davfs_dl580', 'skip::davfs_dl580' ]
  become: True
  tasks:
  - name: mount davfs2 mountpoints
    mount:
      path: /davfs
      src: "https://example.com/remote.php/webdav"
      state: mounted
      fstype: davfs
      opts: "defaults,uid=500,gid=500"
```

Command
```console
(debops) verhaegs@hpdc7800:~/workspace/infra_setup/ansible$ ansible-playbook -l dl580 -t role::davfs_dl580 playbooks/stafverhaegen_cluster.yml 
PLAY [davfs on dl580] ***************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************
ok: [dl580]

TASK [mount davfs2 mountpoints] *****************************************************************************************************************************************************
fatal: [dl580]: FAILED! => {"changed": false, "msg": "Error mounting /davfs: /sbin/mount.davfs: invalid URL\n"}

PLAY RECAP **************************************************************************************************************************************************************************
dl580                      : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

I made sure all paths exists and secrets are properly configured before running the command (will be done later with ansible). Added manually line in /etc/fstab:
```
https://example.com/remote.php/webdav /davfs davfs defaults,uid=500,gid=500 0 0
```
and could mount webdav remote successfully by using `mount /davfs`.

##### EXPECTED RESULTS
Being able to mount davfs mount with ansible.posix

**Comment by Fatsie** [comment]
I changed the state now to present, e.g.:
```yaml
- name: davfs on dl580
  hosts: [ dl580 ]
  tags: [ 'role::davfs_dl580', 'skip::davfs_dl580' ]
  become: True
  tasks:
  - name: mount davfs2 mountpoints
    mount:
      path: /davfs
      src: "https://example.com/remote.php/webdav"
      state: present
      fstype: davfs
      opts: "defaults,uid=500,gid=500"
```
Then the proper line is generated in /etc/fstab and I mount can do `mount /davfs` succesfully so it seems only the mounting from ansible itself that is causing problem.
