### ISSUE TITLE
Release plan

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/ansible.posix#149]
##### SUMMARY
_(partially copied from https://github.com/ansible-collections/community.crypto/issues/74 , thanks to @felixfontein)_

Release minor and patch releases whenever we want (like after adding new features or fixing bugs). Since this collection is small, there's no need to fix things in advance. Just add features, and after a feature either wait a bit longer for more features/bugs, or make a release.

I suggest releasing without branching https://github.com/ansible/community/wiki/ReleasingCollections#releasing-without-release-branches-for-smaller-collections
Breaking changes don't work with this schema but we might change the approach and start releasing from branches when needed.

**Comment by Andersson007** [comment]
I'm going to release 1.2.0 today
https://github.com/ansible-collections/ansible.posix/issues/130

**Comment by ssbarnea** [comment]
@Andersson007 Any idea when the next release will be coming?

I recently seen an important bugfix made by @sshnaidm on https://github.com/ansible-collections/ansible.posix/pull/229 and I need a new release in order to be able to add it as a dependency for molecule-podman module.

**Comment by Akasurde** [comment]
@ssbarnea @Andersson007 I would like to get this https://github.com/ansible-collections/ansible.posix/pull/223 merged before we do the release.

**Comment by sshnaidm** [comment]
we also will need #230

**Comment by Andersson007** [comment]
@ssbarnea good question
CC @saito-hideki , am I right that you recently became a maintainer of the collection? What do you think of releasing it (after @Akasurde 's PR is merged)?

**Comment by saito-hideki** [comment]
Hi @Andersson007, Yeah, I am a newcomer :)
I agree. I think it is reasonable for me to cover #223, #229, and #230.  Also, it is my understanding that #227 is generated from docstring at release time. If my understanding is correct, I will make a change request to fix `firewalld.py` side instead of the RST file before release. What do you think about this idea?

**Comment by Andersson007** [comment]
For me personally, as releases don't happen frequently here (the last one was on March 8), it feels sensible to wait for important things that are **almost ready**. Anyway, i would establish and announce a tentative release date right now to motivate the folks finish / find reviewers for their work before that date:)

**Comment by Akasurde** [comment]
@Andersson007 @saito-hideki  Let us target 8th August 2021, which will give everybody enough time to do their tasks. What's say?

**Comment by saito-hideki** [comment]
@Andersson007 @Akasurde I agree with you guys. thanks! :)

**Comment by Akasurde** [comment]
1.3.0 released on 11 Aug 2021

**Comment by saito-hideki** [comment]
Dear Maintainers,

The next release 1.4.0 is scheduled for the first week of June. Please feel free to comment here if you have any opinions or concerns about that :)

Thanks!

**Comment by chriscroome** [comment]
When the next release it made could it be [released here](https://github.com/ansible-collections/ansible.posix/releases), previous ones have only been [tagged](https://github.com/ansible-collections/ansible.posix/tags) -- I'd like to be able to use Ansible tasks like the following to get the latest version number:

```yml
- name: Use a HEAD request to get the latest redirect URL
  ansible.builtin.uri:
    url: "https://github.com/ansible-collections/ansible.posix/releases/latest"
    method: HEAD
    status_code: 302
    follow_redirects: none
  check_mode: false
  changed_when: false
  register: latest_headers

- name: Set a fact for the latest version
  ansible.builtin.set_fact:
    latest_version: "{{ latest_headers.location | urlsplit('path') | string }}"
```
