### ISSUE TITLE
firewalld module has incorrect port forwarding option proto -> protocol

### ISSUE THREAD

**Issue by ikke-t** [ansible-collections/ansible.posix#176]
##### SUMMARY

```"msg": "ERROR: Exception caught: INVALID_RULE: bad attribute 'proto'"```

[Manual](https://docs.ansible.com/ansible/latest/collections/ansible/posix/firewalld_module.html#parameter-port_forward/proto) says:

```
proto  string  / required | Choices:  udp tcp | protocol to forward
```

Where as the examples has the correct version, it must be ```protocol```, not ```proto```

```
- name: Redirect port 443 to 8443 with Rich Rule
  ansible.posix.firewalld:
    rich_rule: rule family=ipv4 forward-port port=443 protocol=tcp to-port=8443
    zone: public
    permanent: yes
    immediate: yes
    state: enabled
```

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
posix.firewalld

##### ANSIBLE VERSION

latest module version from galaxy
