### ISSUE TITLE
firewalld task is not idempotent for adding ports

### ISSUE THREAD

**Issue by okapia** [ansible-collections/ansible.posix#179]
##### SUMMARY

I'm using the firewalld: task with the port: option. The first time this is run on a host, it works fine. However on any later or subsequent runs, I get an error: ERROR: Exception caught: org.fedoraproject.FirewallD1.Exception: ALREADY_ENABLED: 'xxxxx:tcp' already in 'public' Permanent and Non-Permanent(immediate) operation

This violates idempotency which is really the whole point of ansible.

Aside from port:, I'm using permanent: yes, immediate: yes, state: enabled, and zone: public.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible.posix.firewalld
##### ANSIBLE VERSION

```paste below
ansible 2.10.8

python version = 3.6.8 (default, Mar  9 2021, 15:28:46) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5.0.1)]
```

##### CONFIGURATION

```paste below

```
Problem verified from a plain pip install ansible in a venv and just the minimal task so with zero config. Otherwise I'm not permitted to publish internal paths on the Internet so no full dump.

##### OS / ENVIRONMENT

Oracle Linux 8.3 which is a RHEL 8 clone.

##### STEPS TO REPRODUCE

```yaml
- name: Enable ports in firewall
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
    zone: public
  loop: [ whatever/tcp ]
  become: yes
```

And run this *TWICE*

##### EXPECTED RESULTS

Expected results of the second run to be changed: false, failed: false

##### ACTUAL RESULTS

```paste below
"msg": "ERROR: Exception caught: org.fedoraproject.FirewallD1.Exception: ALREADY_ENABLED: 'myport:tcp' already in 'public' Permanent and Non-Permanent(immediate) operation"
```
