### ISSUE TITLE
Synchronize not using quotes around arguments like --out-format 

### ISSUE THREAD

**Issue by PrestonTaylor** [ansible-collections/ansible.posix#190]
##### SUMMARY
quotes not being places around important arguments 
See here for further details https://github.com/ansible/ansible/issues/46126
Confirmed still buggy in 2.9.6

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Synchronize

##### ANSIBLE VERSION
```ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ptaylo740/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
```

##### CONFIGURATION

```null
```

##### OS / ENVIRONMENT
Ubuntu 20 local Centos 7 remote

##### STEPS TO REPRODUCE

```
  - name: rsync
    synchronize:
      src: /home/centos/somedir/*
      dest: /app/somdir
      rsync_opts:
        - "--exclude='someotherdir'" 
      mode: pull
      compress: no
    delegate_to: "{{ inventory_hostname }}"

```

##### EXPECTED RESULTS
```
/usr/bin/rsync --delay-updates -F --archive --exclude='someotherdir' --out-format='<<CHANGED>>%i %n%L' /home/centos/somedir/* /app/somedir
```

##### ACTUAL RESULTS
```
/usr/bin/rsync --delay-updates -F --archive --exclude='someotherdir' --out-format=<<CHANGED>>%i %n%L /home/centos/somedir/* /app/somedir
```
Notice lack of ' on --out-format
