### ISSUE TITLE
Module ansible.posix.firewalld returns permission denied even with a success change of settings

### ISSUE THREAD

**Issue by lucas-benedito** [ansible-collections/ansible.posix#232]
##### SUMMARY
When setting rich_rule using the module ansible.posix.firewalld, an error is displayed and the task is changed successfully.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
firewall

##### ANSIBLE VERSION
```
2.9.7
```

##### COLLECTION VERSION
```
v1.2.0
```

##### OS / ENVIRONMENT
Red Hat Enterprise Linux Server release 7.9 (Maipo)

##### STEPS TO REPRODUCE
Execute playbook below against an RHEL 7.9 machine.
```
- name: set rich rule
  become: yes
  hosts: all
  tasks:
  - name: Permit incoming connections on port 10050/tcp
    ansible.posix.firewalld:
      rich_rule: rule family="ipv4" source address="xxx.xxx.x.xxx" port port="10050" protocol="tcp" accept
      permanent: yes
      immediate: yes
      state: enabled
```

**redacted source_address** 
##### EXPECTED RESULTS
A changed task without errors.

##### ACTUAL RESULTS
```
<testing.example.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/xxxxxxxxxx testing.example.com '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/ansible/.ansible/tmp `"&& mkdir /home/ansible/.ansible/tmp/ansible-tmp-13548324684.54-97652-135482648752469542 && echo ansible-tmp-13548324684.54-97652-135482648752469542="` echo /home/ansible/.ansible/tmp/ansible-tmp-13548324684.54-97652-135482648752469542 `" ) && sleep 0'"'"''
<testing.example.com> (0, 'ansible-tmp-13548324684.54-97652-135482648752469542=/home/ansible/.ansible/tmp/ansible-tmp-13548324684.54-97652-135482648752469542\n', '')
ERROR: Failed to load '/etc/firewalld/firewalld.conf': [Errno 13] Permission denied: '/etc/firewalld/firewalld.conf'
WARNING: Using fallback firewalld configuration settings.
Using module file /home/ansible/.ansible/collections/ansible_collections/ansible/posix/plugins/modules/firewalld.py
<testing.example.com>
...
TASK [Permit incoming connections on port 10050/tcp] 
changed: [testing.example.com] => {
    "changed": false,
...
```
