### ISSUE TITLE
Interface Management throught 'enabled' and 'disabled' and not 'present'/'absent'

### ISSUE THREAD

**Issue by marcpaulchand** [ansible-collections/ansible.posix#258]
##### SUMMARY

So i've been trying to add an interface to a zone with this task 
```yaml
- name: Add default interface to public
  ansible.posix.firewalld:
    zone: public
    interface: "{{ ansible_default_ipv4.interface }}"
    state: present
    permanent: yes
    immediate: yes
  become: true
```
Refering the documentation, i should use the `absent`or `present` statement.

After some running and running i was still getting this unsuccessfull message 
```console
FAILED! => {"changed": false, "msg": "absent and present state can only be used in zone level operations"}
```

But referring documentation:
```text
= state
        Enable or disable a setting.
        For ports: Should this port accept (enabled) or reject (disabled) connections.
        The states `present' and `absent' can only be used in zone level operations (i.e. when no other parameters but zone and state are set).
        (Choices: absent, disabled, enabled, present)
        type: str
```

After looking at #75 

I change my playbook for `enabled` and it pass !

So does `present` and `absent` still mean something ?
Should the documentation be corrected ?

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
firewalld.py

##### ANSIBLE VERSION

```
ansible 2.9.25
  python version = 3.9.6 (default, Jul 16 2021, 00:00:00) [GCC 11.1.1 20210531 (Red Hat 11.1.1-3)]
```

**Comment by saito-hideki** [comment]
Hi! Thank you for reporting this issue!

From the modules docs:

```The states `present' and `absent' can only be used in zone level operations```

As far as I know, the `zone level` is for creating and deleting zones. If you would like to create a specific zone, you can use `present`. Also you can delete a specific zone using `absent` option. In this case, we need to specify `permanent: yes` and you can't specify `interface` and `immediate` options at  the sametime:

```yaml
- ansible.posix.firewalld:
    zone: custom
    state: present
    permanent: yes
```

Having said that, I think it would be nice if the documentation or error message describes a little more detail :)
