### ISSUE TITLE
firewalld: Support policy objects

### ISSUE THREAD

**Issue by klausenbusk** [ansible-collections/ansible.posix#284]
##### SUMMARY
Firewalld supports "Policy Objects" since v0.9.0:
> With some exceptions (e.g. masquerade, forward-ports) firewalld was previously limited to being an end-station firewall. This meant you could not use it to filter traffic flowing between virtual machines, containers, and zones. A subset of that functionality was available by using the `direct` interface and writing your own `iptables` rules, but it wasn’t a great user experience.
>
> What is needed is a way to apply a policy for traffic flowing between zones. Then the user can attach firewalld’s primitives: services, ports, rich rules, etc. to the policy. The end result is something that provides a very similar user interface to zones, but is much more powerful.

Source: https://firewalld.org/2020/09/policy-objects-introduction

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
firewalld

##### ADDITIONAL INFORMATION

Two informative blog posts:
* https://firewalld.org/2020/09/policy-objects-introduction
* https://firewalld.org/2020/09/policy-objects-filtering-container-and-vm-traffic

Our use-case is similar to the latter blog post (traffic between virtual machines and Wireguard tunnels).

```yaml
- name: create foo policy
  firewalld: policy=foo permanent=yes state=present
  register: result

- name: reload firewalld
  service: name=firewalld state=reloaded
  when: result.changed

- name: set ingress zone for the foo policy
  firewalld: policy=foo ingress_zone=public permanent=yes immediate=yes state=enabled

- name: set egress zone for the foo policy
  firewalld: policy=foo egress_zone=public permanent=yes immediate=yes state=enabled
```
