### ISSUE TITLE
Please add support for firewalld ipsets

### ISSUE THREAD

**Issue by maxxer** [ansible-collections/ansible.posix#293]
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ansible.posix.firewalld

##### ADDITIONAL INFORMATION

https://firewalld.org/documentation/ipset/

It should be possible to add/remove IPs from IPSets, as well as using ipsets as sources or destination for rules.

**Comment by saito-hideki** [comment]
@maxxer Hi! thank you for the feature request! :)

**Comment by GeVa2072** [comment]
See https://github.com/ansible/ansible/issues/37319 
And 
https://github.com/ansible/ansible/pull/49850

**Comment by opoplawski** [comment]
This would be really great to have.

**Comment by nodiscc** [comment]
For what it's worth it's already possible to manage firewalld ipset-based rules with the module, although managing the ipset entries themselves requires a more "manual" approach based on a template:

```yaml
- name: configure firewalld blocklist ipset
  template:
    src: etc_firewalld_ipsets_blocklist.xml.j2
    dest: /etc/firewalld/ipsets/blocklist.xml
    owner: root
    group: root
    mode: "0600"
  notify: reload firewalld

- name: add blocklist ipset to firewalld drop zone
  firewalld:
    zone: drop
    state: enabled
    permanent: yes
    immediate: no
    source: "ipset:blocklist"
  notify: reload firewalld
```
```xml
$ cat roles/common/templates/etc_firewalld_ipsets_blocklist.xml.j2 
<?xml version="1.0" encoding="utf-8"?>
  <ipset type="hash:net">
  <short>blocklist</short>
{% for item in firewalld_blocklist %}
  <entry>{{ item }}</entry>
{% endfor %}
</ipset>
```
```yaml
# roles/firewalld/defaults/main.yml
# list of IP addresses/networks to block globally
# Example:
# firewalld_blocklist:
#   - 1.2.3.4
#   - 5.6.7.8/24
#   - 9.10.11.12/16
firewalld_blocklist: []
```
