### ISSUE TITLE
sysctl: add option to remove the extra options from the manages files

### ISSUE THREAD

**Issue by Ph0enix89** [ansible-collections/ansible.posix#294]
##### SUMMARY

Add a new option to manage the content of the file exclusively by the module and delete all variables that are not part of parameter list in the playbook.
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

sysctl

##### ADDITIONAL INFORMATION

As part of the workflows in our organization we manage forwarding on network interfaces via `sysctl`. The problem is that every now and then the interface names change (e.g. some bridges are created or removed). Currently that means that we either need to have a run with the variables in question marked as `absent` and then remove them from the config (which seems like an avoidable overhead) or use templates to ensure that if the config is modified and some variables are deleted then they do not stay in the corresponding file on the system.

Having an option to tell `sysctl` to either handle each config variable independently (current behavior) or to manage the whole file and stip away all the parameters that are not mentioned in the playbook

```yaml
- name: Manage forwarding
  sysctl:
    state: present
    sysctl_file: '/etc/sysctl.d/90-net-fwd.conf'
    exclusive: yes
    name: 'net.ipv4.conf.eno1.forwarding'
    value: '1'


```
