### ISSUE TITLE
Using posix.mount in AAP 2.1 throws: Unable to apply new capability set

### ISSUE THREAD

**Issue by fhamed** [ansible-collections/ansible.posix#310]
##### SUMMARY

Using the module mount in Ansible Platform 2.1, which runs playbooks within containers, throws the following error:
"Unable to apply new capability set."

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

posix.mount

##### ANSIBLE VERSION

```paste below

VERSIONS (via ansible-navigator):

ansible:
collections:
  details:
    ansible.posix: 1.2.0
    ansible.utils: 2.4.2
    community.general: 4.2.0
	...
version:
  details: core 2.12.1

OS:
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"

podman version 3.3.1
```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

- name: Mount task
  become: true
  ansible.posix.mount:
    path: /tmp/test
    src: 10.xx.xx.14/pac
    fstype: cifs
    opts: "rw,vers=3.0,dir_mode=0777,file_mode=0777,serverino,username=myuser,password=mypass"
    state: mounted
  delegate_to: localhost

```

##### ACTUAL RESULTS

```paste below

```
