### ISSUE TITLE
Synchronize module cannot use SSH multiplexing if ControlPath is autogenerated

### ISSUE THREAD

**Issue by eszense** [ansible-collections/ansible.posix#317]
##### SUMMARY
- If `ControlMaster` and `ControlPersist` is specified in `ssh_args` of ansible.cfg, the omitted `ControlPath` will be autogenerated by ansible with `~/.ansible/cp/<digest of user-host-port>` as per [the ssh connection plugin](https://github.com/ansible/ansible/blob/f501b579e51c05565d852feb676fa38cddf3f2ed/lib/ansible/plugins/connection/ssh.py#L570)
- This autogenerated `ControlPath` is not picked up by the `synchronize` when `ssh_connection_multiplexing` and `use_ssh_args` is enabled, leading to failure in multiplexing
- This is not only a performance issue. In my case I use Yubikey for SSH authentication, and relies on multiplexing on a single SSH connection to remains authenticated (Can't use ssh-agent). Failure in multiplexing will lead to me having to touch the Yubikey for *each* invocation of synchronize task.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
synchronize

##### ANSIBLE VERSION
```ansible [core 2.12.0]
  python version = 3.9.7 (v3.9.7:1016ef3790, Aug 30 2021, 16:39:15) [Clang 6.0 (clang-600.0.57)]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION
```
Collection                    Version
----------------------------- -------
ansible.posix                 1.3.0  
```

##### OS / ENVIRONMENT
Controller: MacOS Big Sur
Target: Ubuntu Impish

##### STEPS TO REPRODUCE
 - Disable your ssh-agent
 - Add ssh_args in ansible.cfg 
```[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=1200
```
 - Run this playbook
```
---
- hosts: MY_HOST
  tasks:
    - command: echo This task used multiplexing and no reauthentication needed
    - synchronize: # This failed multiplexing and need reauthentication
        src: ~/tmp
        dest: ~/tmp
```
 - Connect to a host

##### EXPECTED RESULTS
When `ssh_connection_multiplexing` and `use_ssh_args` are enabled, synchronize module is expected to reuse all ssh_args, especially the implicit `ControlPath`

##### ACTUAL RESULTS
Implicit `ControlPath` not reused
