### ISSUE TITLE
authorized_key: allow list of keys/urls

### ISSUE THREAD

**Issue by Yajo** [ansible-collections/ansible.posix#323]
##### SUMMARY

Let this module handle multiple keys/urls with just one invocation.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

authorized_key

##### ADDITIONAL INFORMATION

This would let us use the module with `exclusive: true` even when we're adding more than one key at once.

We can still forge this with a combination of jinja templates and the url lookup, but this would make it clearer.

```yaml
# Now
authorized_key:
  exclusive: true
  key: |
    {{ lookup('url', 'https://github.com/Yajo.keys', split_lines=false) }}
    {{ lookup('url', 'https://github.com/other.keys', split_lines=false) }}

# Proposal
authorized_key:
  exclusive: true
  key:
    - https://github.com/Yajo.keys
    - https://github.com/other.keys
```
