### ISSUE TITLE
Date and time scheduling for At module

### ISSUE THREAD

**Issue by DaneHoffman** [ansible-collections/ansible.posix#326]
##### SUMMARY

A `timedate` option for the `at` module

The `at` module in its present state only supports a timed delay in seconds, whereas the `at` linux command supports scheduling a command based on the date and/or time of day. It would be helpful to include this functionality in the Ansible `at` module as well.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`at`

##### ADDITIONAL INFORMATION

An example of a situation where this would be useful is after a server upgrade. An admin may want to schedule a system reboot at a certain time of day to minimize the impact of downtime on users. The `count` and `units` options would not be helpful in this instance.

```yaml
---

- hosts: all
  become: true
  gather_facts: no
  tasks:

    - name: Schedule reboot for 2:00 AM
      at:
        cmd: "reboot now"
        timedate: 2:00 AM
        # or
        # timedate: tomorrow


```
