### ISSUE TITLE
authorized_key module always reports 'changed' when using key_options

### ISSUE THREAD

**Issue by cudevmaxwell** [ansible-collections/ansible.posix#327]
##### SUMMARY

When using the `authorized_key` module, tasks which use the `key_options` parameter always fire 'changed'.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

authorized_key 

##### ANSIBLE VERSION

```paste below
ansible 2.9.27
```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Linux - Fedora release 35 (Thirty Five)

##### STEPS TO REPRODUCE

```yaml
# Not a real key below
- name: Add key to authorized_keys file
  authorized_key:
    user: "borg-user"
    state: present
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP9Z7HlUQ0Dk+nDmedLG7I9DYDcHN6iv/nuCDViFOEYr Borg backup key"
    key_options: "command=\"borg serve --append-only --restrict-to-path /home/borg-user/backup\",restrict "
```

##### EXPECTED RESULTS

Initial run shows changed, next run shows not changed. 

##### ACTUAL RESULTS

Initial run shows changed, next run shows changed, even though authorized_keys file did not change.

**Comment by nlvw** [comment]
I get this same behaviour even when I use a `default(omit)` jinja value.

```yaml
- name: set authorized keys
  authorized_key:
    user: "{{ item.user }}"
    state: "{{ item.state | default('present') }}"
    key: "{{ item.key }}"
    key_options: "{{ item.key_options | default(omit) }}"
    comment: "{{ item.comment | default(omit) }} "
    exclusive: "{{ item.exclusive | default(omit) }}"
    manage_dir: "{{ item.manage_dir | default(omit) }}"
    path: "{{ item.path | default(omit) }}"
    validate_certs: "{{ item.validate_certs | default(omit) }}"
  with_items: "{{ users_merged_authkeys }}"
  when:
    - (item.user is defined) and (item.user | length > 0)
    - (item.key is defined) and (item.key | length > 0)
```

With list item:

```yaml
 - user: tester
    comment: tester@example.com
    key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILiChtXZDvU1G5oCwaoDHXoecnfMo7ff8w6k4zoG8OK6'
    exclusive: yes
    state: present
```
