### ISSUE TITLE
Less verbose synchronize module output

### ISSUE THREAD

**Issue by bluikko** [ansible-collections/ansible.posix#341]
##### SUMMARY

Currently the `synchronize` module output is very verbose.  
On level `-vv` the same rsync output, including line for each transferred item, is printed 3 times:
- I do not know how to call this output; it is the direct rsync output with default terminal color with seemingly no formatting or mangling whatsoever.
- The `msg` var printed in yellow color.
- The `stdout_lines` var printed in yellow color.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

synchronize

##### ADDITIONAL INFORMATION

If several thousand -- or even tens of thousands, by no means an unreasonable possibility -- files are being synchronized it seems excessive, even if I had requested verbosity with `-vv`.  
A couple of different things could be possible:
- Make the `stdout_lines` print only as `<omitted>`, same as the `command` module does.  
  This could be the minimum change if it is possible reasonably.
- Instead of printing each transferred item in its own line due to `rsync` option `--out-format=[...]`, could the various different "summary" data that `rsync` prints give the information that the module needs?  
  Example of such a summary below.

```console
Number of files: 4,497 (reg: 4,437, dir: 60)
Number of created files: 4,496 (reg: 4,437, dir: 59)
Number of deleted files: 0
Number of regular files transferred: 4,437
Total file size: 37,086,484,092 bytes
Total transferred file size: 37,086,484,092 bytes
Literal data: 37,086,484,092 bytes
Matched data: 0 bytes
File list size: 65,534
File list generation time: 0.074 seconds
File list transfer time: 0.000 seconds
Total bytes sent: 37,095,880,814
Total bytes received: 84,830

sent 37,095,880,814 bytes  received 84,830 bytes  68,003,603.38 bytes/sec
total size is 37,086,484,092  speedup is 1.00
```

It does not seem useful to print the same information 3 times when the content could be thousands or tens of thousands of lines.  
Turning the itemized output off with a suitable `rsync_opt` switch makes the task not detect whether it was `changed`. So obviously some output is needed for making the decision whether the task was `changed`, `failed`, etc. Possibly the necessary information could be parsed out of `rsync` summary data block instead of the long itemized output?

Example output from `synchronize`:

```yaml
TASK [Copy files] *************************************************************************************************************************************************************
task path: /ansible/testcopy.yml:50
.d..tp..... ./
>f+++++++++ testfile0000
[...]
changed: [host.example.com -> host.example.com] => changed=true
  cmd: /usr/bin/rsync --archive --out-format='<<CHANGED>>%i %n%L' /source/ /destination
  msg: |-
    .d..tp..... ./
    >f+++++++++ testfile0000
[...]
  rc: 0
  stdout_lines:
  - .d..tp..... ./
  - '>f+++++++++ testfile0000'
[...]
```
Each of the three [...] above is to replace the full list of thousands of files/directories.

**Comment by vbotka** [comment]
The main problem is that you **can't override** the option

```
--out-format='<<CHANGED>>%i %n%L'
```

You can control the output without the option *--out-format* and with the option *--info*. For example, given the simple tree below

```bash
shell> tree /tmp/ansible/
/tmp/ansible/
├── dest
└── src
    ├── a
    ├── b
    └── c
```
You can ask for statistics and no files

```bash
shell> rsync -a --info=name0,stats2 /tmp/ansible/src/ /tmp/ansible/dest

Number of files: 4 (reg: 3, dir: 1)
Number of created files: 3 (reg: 3)
Number of deleted files: 0
Number of regular files transferred: 3
Total file size: 0 bytes
Total transferred file size: 0 bytes
Literal data: 0 bytes
Matched data: 0 bytes
File list size: 0
File list generation time: 0.001 seconds
File list transfer time: 0.000 seconds
Total bytes sent: 227
Total bytes received: 76

sent 227 bytes  received 76 bytes  606.00 bytes/sec
total size is 0  speedup is 0.00
```

The below command shows nothing at all

```bash
shell> rsync -a --info=name0 /tmp/ansible/src/ /tmp/ansible/dest
```

Unfortunately, this doesn't work with the module *synchronize*. You can set [rsync_opts](https://docs.ansible.com/ansible/latest/collections/ansible/posix/synchronize_module.html#parameter-rsync_opts)

```yaml
    - synchronize:
        src: /tmp/ansible/src/
        dest: /tmp/ansible/dest
        rsync_opts:
          - --info=name0,stats2
          - --out-format=""
      register: changed_files
```
, but you can't override **--out-format='<<CHANGED>>%i %n%L'**

```yaml
  changed_files:
    changed: true
    cmd: /usr/bin/rsync --delay-updates -F --compress --archive --info=name0,stats2 --out-format="" --out-format='<<CHANGED>>%i %n%L' /tmp/ansible/src/ /tmp/ansible/dest
    failed: false
    msg: |-
      .d..t...... ./
      >f+++++++++ a
      >f+++++++++ b
      >f+++++++++ c
  
      Number of files: 4 (reg: 3, dir: 1)
      Number of created files: 3 (reg: 3)
      Number of deleted files: 0
      Number of regular files transferred: 3
      Total file size: 0 bytes
      Total transferred file size: 0 bytes
      Literal data: 0 bytes
      Matched data: 0 bytes
      File list size: 0
      File list generation time: 0.001 seconds
      File list transfer time: 0.000 seconds
      Total bytes sent: 232
      Total bytes received: 80
  
      sent 232 bytes  received 80 bytes  624.00 bytes/sec
      total size is 0  speedup is 0.00
    rc: 0
    stdout_lines:
    - .d..t...... ./
    - '>f+++++++++ a'
    - '>f+++++++++ b'
    - '>f+++++++++ c'
    - 'Number of files: 4 (reg: 3, dir: 1)'
    - 'Number of created files: 3 (reg: 3)'
    - 'Number of deleted files: 0'
    - 'Number of regular files transferred: 3'
    - 'Total file size: 0 bytes'
    - 'Total transferred file size: 0 bytes'
    - 'Literal data: 0 bytes'
    - 'Matched data: 0 bytes'
    - 'File list size: 0'
    - 'File list generation time: 0.001 seconds'
    - 'File list transfer time: 0.000 seconds'
    - 'Total bytes sent: 232'
    - 'Total bytes received: 80'
    - sent 232 bytes  received 80 bytes  624.00 bytes/sec
    - total size is 0  speedup is 0.00
```

This should be considered a bug. Fixing this bug would solve this feature request.

No triage is needed.

**Comment by codeshell** [comment]
I support the opinion that this is a bug.

_On a personal note: Setting `--stats` in options and debug printing that sync result out as helpful summary only to end up with tens of thousands of lines in the task log breaking your management database due to some hidden forced argument is no fun._

Even if this approach is necessary as long as the user wants the module to indentify changes reliably, I cannot find any valid reason to not allow the user to opt out of "built-in change detection with --out-format".

On the other hand, I find two reasons to make change detection optional:
1. Even now, a user can tell rsync to `--quiet` so the change detection does not work anyway in every context as is. (Obviously, this skips any other info like our summary as well so `--quiet`  is not a solution to this issue)
2. The user is able to do something the module cannot do: Identify changes without "--info=name" (which is force-set by --out-format), e.g. from stats. It might be localized or have other reasons why it did not fit the maintainers bill.

## Workaround

The following offers a workaround to only print the summary:

1. Enable stats with `--stats` or `--info=stats2`. ( Example see https://github.com/ansible-collections/ansible.posix/issues/341#issuecomment-2265746898 by vbotka)
2. Use Jinja to only get the last lines like this: `"{{ sync_result.stdout_lines[-15:] | join('\n') }}"`

Example with more context below.

## Example with alternate user-defined change detection

The following also adds a PoC to get the change state just from those 15 lines.

Please keep in mind that the module-added "--out-format" overwrites info flags so "--info=name0" gets ignored and we need to apply the workaround to prevent log flooding.

```yaml
    - name: Sync files to remote host
      ansible.posix.synchronize:
        src: "{{ s }}/"
        dest: "{{ t }}/"
        rsync_opts:
          - --info=stats2,misc1,flist0,name0,progress0
          # - --out-format=""
          # - --stats
          # - --quiet
      register: sync_result

    - name: Display sync command
      ansible.builtin.debug:
        var: sync_result.cmd
    
    - name: Display the last 15 sync-result lines
      ansible.builtin.debug:
        msg: "{{ sync_result.stdout_lines[-15:] | join(' || ') }}"
      changed_when: >-
        (
          sync_result.stdout_lines[-15:]
          | join('\n')
          | regex_findall('ed files: 0')
          | length
        ) != 2

```
