### ISSUE TITLE
ansible.posix.synchronize

### ISSUE THREAD

**Issue by jesulo** [ansible-collections/ansible.posix#358]
##### SUMMARY

{"ansible_loop_var": "item", "changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh='/usr/bin/ssh -S none -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' --out-format='<>%i %n%L' /opt/springboot/sxxx/xxxx.jar root@10.2.1.2:/opt/springboot/xxxxx"

Ansible 2.9 say it make change ok but not copy file

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

synchronizer

##### ANSIBLE VERSION

```paste below
2.9
```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

rhel 8

##### STEPS TO REPRODUCE

```yaml

  - name: Copiar mismos archivos entre servidores
    ansible.posix.synchronize:
      src: "{{ item.0 }}"
      dest: "{{ item.1 }}/"
      become: true
      become_user: root
    delegate_to: "10.1.1.1"
    with_together:
      - "{{my_results_final}}"
      - "{{my_results_final2}}"
```

##### ACTUAL RESULTS

```paste below

```
