### ISSUE TITLE
Synchronize is using a lot of memory during sync of many files

### ISSUE THREAD

**Issue by lmm-git** [ansible-collections/ansible.posix#377]
##### SUMMARY
Synchronize is using a lot of memory during sync (some may also call it leaking)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Synchronize

##### ANSIBLE VERSION

```
ansible [core 2.13.1]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.5 (default, Nov 18 2021, 16:00:48) [GCC 10.3.0]
  jinja version = 3.1.2
  libyaml = True

```

##### COLLECTION VERSION

```paste below
# /usr/local/lib/python3.9/dist-packages/ansible_collections
Collection    Version
------------- -------
ansible.posix 1.4.0  

```

##### OS / ENVIRONMENT

Linux, but should affect all OS

##### STEPS TO REPRODUCE

```yaml
- name: Synchronization of OS image
  ansible.posix.synchronize:
    src: /imager/image/
    dest: "{{ imager_mount_dir_new_image }}/"
    archive: yes
    checksum: yes
    verify_host: yes
    delay_updates: no
    rsync_timeout: 60
    rsync_opts:
      # use rsync `--delete-during` instead the default `delete`, which results in `--delete-after` imposing higher ram usage
      - '--delete-during'
      # use --ignore-times to calculate the checksum for all files even if size and time is equal
      - '--ignore-times'
```

##### EXPECTED RESULTS

No significant RAM increase

##### ACTUAL RESULTS

RAM usage rises up to a few hundred Megabytes for ~240k  files.

All RAM gets freed when there is no error or the log output gets printed (which was > 50MB in some cases) on error.

##### Technical Details

I suspect the RAM leakage coming from https://github.com/ansible-collections/ansible.posix/blob/6da0cbb3d37b9463dd3115d6755ed0d49eb4db9c/plugins/modules/synchronize.py#L582 as this order rsync to print every changed file (which by itself should be fine). As in this line <https://github.com/ansible-collections/ansible.posix/blob/6da0cbb3d37b9463dd3115d6755ed0d49eb4db9c/plugins/modules/synchronize.py#L609> it rsync is called synchronously, which results in the whole output written to the variable `out` or `err`. As the output might get really large for many files, it might be better to stream it to a temporary file or directly process it line by line (also streaming).

Furthermore, the processing of the output in the following lines might be quite inefficient depending on the number of empty lines: https://github.com/ansible-collections/ansible.posix/blob/6da0cbb3d37b9463dd3115d6755ed0d49eb4db9c/plugins/modules/synchronize.py#L622-L623

Just adding a quiet switch to rsync does not help directly, as this will impose the loss of the changed status of the job.
