### ISSUE TITLE
Synchronize cannot find directories from sub roles like copy does

### ISSUE THREAD

**Issue by Zocker1999NET** [ansible-collections/ansible.posix#381]
##### SUMMARY

When role A includes role B as dependency, role B can access files & templates from role A's directories using a relative path if this path does not exists in its own directories. This works for nearly all builtin modules from Ansible (if I remember correctly, this is documented, but I don't know where). This also works for the copy module but not for synchronize.

I marked it as a feature request, because this feature is nowhere stated for synchronize itself.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ansible.posix.synchronize

##### ADDITIONAL INFORMATION

This feature helps to e.g. create a role managing a docker-compose project in general (upload repo with docker-compose.yml and Dockerfiles, build & launch compose, configure other stuff required, …), further called "role_b", which can be reused by multiple roles holding the repo with docker-compose.yml and Dockerfiles for certain services, further called "role_a".

The multi file example I describe below shows what works with copy and what I want to do with synchronize:

<details>
<summary>Example files with contents</summary>

#### site.yml

```yaml
# run example locally
- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: role_a
```

#### roles/role_a/meta/main.yml

```yaml
# this role holds a repo in its files/ directory

dependencies:
  # include role with copy/synchronize
  - name: role_b
```

#### roles/role_a/files/repo/docker-compose.yml

```yaml
# Imagine a docker-compose.yml using multiple Dockerfiles …
```

#### roles/role_a/files/repo/Dockerfile

```yaml
# Imagine multiple Dockerfiles used by docker-compose.yml
```

#### roles/role_b/tasks/main.yml

```yaml
# check_mode so nothing will be applied

# this works
- name: Copy temp
  check_mode: yes
  ansible.builtin.copy:
    src: dir/
    dest: /tmp

# this not
- name: Sync temp
  check_mode: yes
  ansible.posix.synchronize:
    mode: push
    src: dir/
    dest: /tmp
  ignore_errors: yes
```

</details>

**Comment by mnaser** [comment]
@Zocker1999NET I pushed up your change into a PR since it's been quite a few months since you brought it up :)

**Comment by Zocker1999NET** [comment]
@mnaser Thanks, I already forgot about that :+1:

**Comment by paulcalabro** [comment]
In case anyone else bumps into this issue, one workaround is to use `ansible.builtin.first_found`.

**ansible_search_path**:
>  This lookup checks a list of files and paths and returns the full path to the first combination found.
>
> **As all lookups, when fed relative paths it will try use the current task’s location first and go up the chain to the containing locations of role / play / include and so on.**
>
> The list of files has precedence over the paths searched. For example, A task in a role has a ‘file1’ in the play’s relative path, this will be used, ‘file2’ in role’s relative path will not.
>
> Either a list of files [_terms](https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/first_found_lookup.html#ansible-collections-ansible-builtin-first-found-lookup-parameter-terms) or a key [files](https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/first_found_lookup.html#ansible-collections-ansible-builtin-first-found-lookup-parameter-files) with a list of files is required for this plugin to operate.

e.g.,

```
- name: Deploy the files.
  vars:
    _files: files/drop-ins/
    _found_file: >-
      {{
        lookup('ansible.builtin.first_found', files=_files)
      }}
  ansible.posix.synchronize:
    dest: /some/path/
    src: "{{ _found_file }}"
```
