### ISSUE TITLE
firewalld ERROR: Exception caught: FirewallClient.queryForwardPort() got an unexpected keyword argument 'to_port'"

### ISSUE THREAD

**Issue by jsalatiel** [ansible-collections/ansible.posix#382]
##### SUMMARY
Trying to use the portforward options leads to error.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
firewalld

##### ANSIBLE VERSION

```
ansible [core 2.11.11]
```
##### STEPS TO REPRODUCE

```yaml
- name: Forward  example
  firewalld:
    port_forward:
    - port: 2222
      proto: tcp
      toport: 22
    state: enabled
    immediate: true
    permanent: true

```

##### EXPECTED RESULTS

Port 2222 should be redirect to port 22

##### ACTUAL RESULTS

FAILED! => {"changed": false, "msg": "ERROR: Exception caught: FirewallClient.queryForwardPort() got an unexpected keyword argument 'to_port'"}

```paste below

```
