### ISSUE TITLE
synchronize: get {"msg": "Could not find the shell plugin required (bash)."}

### ISSUE THREAD

**Issue by mamh2021** [ansible-collections/ansible.posix#392]
##### SUMMARY
\
run one playbook like below:
```
---                        
- hosts: centos     
  become: False    
  gather_facts: False
  tasks:
    - name: "Synchronize and delete files for categraf"
      ansible.posix.synchronize:
        src: /work/jenkins/workspace/categraf/
        dest: categraf/
        delete: yes
        recursive: yes


```

synchronize: get {"msg": "Could not find the shell plugin required (bash)."}

my  ansible.cfg file  set executable = /bin/bash

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```
