### ISSUE TITLE
ansible.posix.mount doesn't escape tab characters

### ISSUE THREAD

**Issue by Xeicker** [ansible-collections/ansible.posix#427]
##### SUMMARY
- As man page of fstab states, tabs should be escaped as `\011` but this is not being done as i see here https://github.com/ansible-collections/ansible.posix/blob/main/plugins/modules/mount.py#L255:~:text=def%20_escape_fstab(,%5C%5C046%27)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible.posix.mount

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.7]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ~/.local/lib/python3.8/site-packages/ansible
  ansible collection location =~/.ansible/collections:/usr/share/ansible/collections
  executable location = ~/.local/bin/ansible
  python version = 3.8.13 (default, Oct  3 2022, 09:59:16) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15.0.1)]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below

# ~/.local/lib/python3.8/site-packages/ansible_collections
Collection    Version
------------- -------
ansible.posix 1.4.0
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
```

##### OS / ENVIRONMENT

OL8

##### STEPS TO REPRODUCE

set an entry in fstab with a tab character in the mountpoint string

```
echo "label=remote /store\040mount\011point nfs rw,nosuid,nodev 0 0" >> /etc/fstab
```
and then run the playbook

```yaml
- hosts: all
  tasks:
    - name: Get nfs and nfs4 mount points, that don't have noexec
      command: findmnt --fstab --types nfs,nfs4 -O nonoexec -n -P
      register: points_register
      check_mode: false
      changed_when: false
      failed_when: false

    - name: Add noexec to nfs and nfs4 mount points
      mount:
        path: '{{ item | regex_search(''TARGET="([^"]+)"'',''\1'') | first }}'
        src: '{{ item | regex_search(''SOURCE="([^"]+)"'',''\1'') | first }}'
        fstype: '{{ item | regex_search(''FSTYPE="([^"]+)"'',''\1'') | first }}'
        state: present
        opts: '{{ item | regex_search(''OPTIONS="([^"]+)"'',''\1'') | first }},noexec'
      when: (points_register.stdout | length > 0) 
      with_items: '{{ points_register.stdout_lines }}'
```

##### EXPECTED RESULTS
The entry should be updated to include the "noexec" option in existing entry

##### ACTUAL RESULTS
A new entry is created like this:

``` bash
# grep remote /etc/fstab 
label=remote /store\040mount\011point nfs rw,nosuid,nodev 0 0
label=remote /store\040mount\134x09point nfs rw,nosuid,nodev,noexec 0 0
```
