### ISSUE TITLE
ansible.posix.firewalld  permanent rule issue.

### ISSUE THREAD

**Issue by ysakkk** [ansible-collections/ansible.posix#451]
When I add a "permanent" rule in the following environment, all tcp communication permission rules are added with no change in the execution result.
```
OS: Rocky Linux release 9.1 (Blue Onyx)
ansible: ansible-core-2.13.3-2.el9_1.x86_64

* requirements.yml
collections:
  - name: community.general
  - name: ansible.posix

* install 
$ ansible-galaxy  install -r requirements.yml

* roles/firewall/tasks/main.yml
- name: "allow /etc/firewalld/zones/public.xml"
  ansible.posix.firewalld:
    port: "1111/tcp"
    permanent: true    ### here
    state: enabled 

$ ansible-playbook firewall.yml
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  


# diff  /etc/firewalld/zones/public.xml{,.old}
10d9
<   <protocol value="tcp"/>
```

**Comment by rekup** [comment]
This is a huge issue! The line `<protocol value="tcp"/>` in the zone file results in all tcp connections being accepted. This is reproducable using a simple task:

```yaml
    - name: open ports
      ansible.posix.firewalld:
        port: "25/tcp"
        permanent: yes
        immediate: yes
        state: enabled
        zone: "public"
```

Afterwards test using nc:

on the server:

```bash
[user@server]# nc -l 1234
```

On the client:

```bash
echo "this is a huege problem" | nc <ip> 1234
```

Back on the server:

```bash
[user@server]# nc -l 1234
this is a huege problem
```

This potentially leaves many servers exposed.

CC @felixfontein, @maxamillion
