### ISSUE TITLE
mount module with opts: bind is not idempotent/always creates a new mount

### ISSUE THREAD

**Issue by nodiscc** [ansible-collections/ansible.posix#459]
##### SUMMARY
When a task that uses the `mount` module with `opts: bind` is called multiple times, it always returns `changed`, and creates a new mount in `/etc/mtab`.

I believe this was already reported in https://github.com/ansible/ansible/issues/29870, https://github.com/ansible/ansible/issues/23487, https://github.com/ansible/ansible/issues/8422, https://github.com/ansible/ansible/issues/7121 which were closed while the problem was not actually fixed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mount

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible [core 2.14.5]
  config file = /home/live/GIT/ansible-playbook-infra.git/ansible.cfg
  configured module search path = ['/home/live/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/live/playbooks/default/.venv/lib/python3.9/site-packages/ansible
  ansible collection location = /home/live/GIT/ansible-playbook-infra.git
  executable location = /home/live/playbooks/default/.venv/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/home/live/playbooks/default/.venv/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
$ ansible-galaxy collection list ansible.posix

# /home/live/playbooks/default/.venv/lib/python3.9/site-packages/ansible_collections
Collection    Version
------------- -------
ansible.posix 1.5.2  

```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed -t all
Using /home/live/GIT/ansible-playbook-infra.git/ansible.cfg as config file
CACHE_PLUGIN(/home/live/GIT/ansible-playbook-infra.git/ansible.cfg) = yaml
CACHE_PLUGIN_CONNECTION(/home/live/GIT/ansible-playbook-infra.git/ansible.cfg) = data/cache/facts/
COLLECTIONS_PATHS(/home/live/GIT/ansible-playbook-infra.git/ansible.cfg) = ['/home/live/GIT/ansible-playbook-infra.git']
CONFIG_FILE() = /home/live/GIT/ansible-playbook-infra.git/ansible.cfg
DEFAULT_GATHERING(/home/live/GIT/ansible-playbook-infra.git/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/live/GIT/ansible-playbook-infra.git/ansible.cfg) = ['/home/live/GIT/ansible-playbook-infra.git/inventory.yml']
DEFAULT_LOG_PATH(/home/live/GIT/ansible-playbook-infra.git/ansible.cfg) = /home/live/GIT/ansible-playbook-infra.git/ansible.log
DEFAULT_PRIVATE_KEY_FILE(/home/live/GIT/ansible-playbook-infra.git/ansible.cfg) = /home/live/.ssh/id_rsa
DEFAULT_ROLES_PATH(/home/live/GIT/ansible-playbook-infra.git/ansible.cfg) = ['/home/live/GIT/ansible-playbook-infra.git/roles']
DEFAULT_STDOUT_CALLBACK(/home/live/GIT/ansible-playbook-infra.git/ansible.cfg) = ansible.posix.debug
DEFAULT_VAULT_PASSWORD_FILE(/home/live/GIT/ansible-playbook-infra.git/ansible.cfg) = /home/live/GIT/ansible-playbook-infra.git/.ansible-vault-password
DEFAULT_VERBOSITY(/home/live/GIT/ansible-playbook-infra.git/ansible.cfg) = 1
DIFF_ALWAYS(/home/live/GIT/ansible-playbook-infra.git/ansible.cfg) = True
INTERPRETER_PYTHON(/home/live/GIT/ansible-playbook-infra.git/ansible.cfg) = /usr/bin/python3
RETRY_FILES_ENABLED(/home/live/GIT/ansible-playbook-infra.git/ansible.cfg) = True

CACHE:
=====

jsonfile:
________
_uri(/home/live/GIT/ansible-playbook-infra.git/ansible.cfg) = /home/live/GIT/ansible-playbook-infra.git/data/cache/facts

CONNECTION:
==========

paramiko_ssh:
____________
ssh_args(/home/live/GIT/ansible-playbook-infra.git/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=3600s -o PreferredAuthentications=publickey

ssh:
___
pipelining(/home/live/GIT/ansible-playbook-infra.git/ansible.cfg) = True
private_key_file(/home/live/GIT/ansible-playbook-infra.git/ansible.cfg) = ~/.ssh/id_rsa
ssh_args(/home/live/GIT/ansible-playbook-infra.git/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=3600s -o PreferredAuthentications=publickey
```

##### OS / ENVIRONMENT

Debian 11 controller, Debian 11 host

##### STEPS TO REPRODUCE

```yaml (paste below)
$ cat roles/jellyfin/tasks/main.yml 
- name: mount jellyfin samba share to jellyfin directory
  become: yes
  mount:
    path: /var/lib/jellyfin/sambashare
    src: "/var/lib/samba/shares/jellyfin"
    opts: bind
    state: mounted
    fstype: none

$ cat playbook.yml
- hosts: example.org
  roles:
    - jellyfin
```

```bash
$ ansible-playbook playbook.yml
```

##### EXPECTED RESULTS

The task should only return `changed` (and create a mount) the first time it is called. Subsequent runs should not change anything, and return `changed: false`.

##### ACTUAL RESULTS

```console
...
TASK [jellyfin : mount jellyfin samba share to jellyfin directory] ******************************************************
changed: [example.org] => {
    "backup_file": "",
    "boot": "yes",
    "changed": true,
    "dump": "0",
    "fstab": "/etc/fstab",
    "fstype": "none",
    "name": "/var/lib/jellyfin/sambashare",
    "opts": "bind",
    "passno": "0",
    "src": "/var/lib/samba/shares//jellyfin"
}
```

After running this task multiple times:

```
$ mount|grep jellyfin
/dev/mapper/debian11--base--vg-root on /var/lib/jellyfin/sambashare type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/debian11--base--vg-root on /var/lib/jellyfin/sambashare type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/debian11--base--vg-root on /var/lib/samba/shares/jellyfin type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/debian11--base--vg-root on /var/lib/jellyfin/sambashare type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/debian11--base--vg-root on /var/lib/samba/shares/jellyfin type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/debian11--base--vg-root on /var/lib/jellyfin/sambashare type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/debian11--base--vg-root on /var/lib/samba/shares/jellyfin type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/debian11--base--vg-root on /var/lib/jellyfin/sambashare type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/debian11--base--vg-root on /var/lib/samba/shares/jellyfin type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/debian11--base--vg-root on /var/lib/jellyfin/sambashare type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/debian11--base--vg-root on /var/lib/samba/shares/jellyfin type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/debian11--base--vg-root on /var/lib/jellyfin/sambashare type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/debian11--base--vg-root on /var/lib/samba/shares/jellyfin type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/debian11--base--vg-root on /var/lib/jellyfin/sambashare type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/debian11--base--vg-root on /var/lib/samba/shares/jellyfin type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/debian11--base--vg-root on /var/lib/jellyfin/sambashare type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/debian11--base--vg-root on /var/lib/samba/shares/jellyfin type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/debian11--base--vg-root on /var/lib/jellyfin/sambashare type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/debian11--base--vg-root on /var/lib/samba/shares/jellyfin type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/debian11--base--vg-root on /var/lib/jellyfin/sambashare type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/debian11--base--vg-root on /var/lib/samba/shares/jellyfin type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/debian11--base--vg-root on /var/lib/jellyfin/sambashare type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/debian11--base--vg-root on /var/lib/samba/shares/jellyfin type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/debian11--base--vg-root on /var/lib/jellyfin/sambashare type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/debian11--base--vg-root on /var/lib/samba/shares/jellyfin type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/debian11--base--vg-root on /var/lib/jellyfin/sambashare type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/debian11--base--vg-root on /var/lib/samba/shares/jellyfin type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/debian11--base--vg-root on /var/lib/jellyfin/sambashare type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/debian11--base--vg-root on /var/lib/samba/shares/jellyfin type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/debian11--base--vg-root on /var/lib/jellyfin/sambashare type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/debian11--base--vg-root on /var/lib/samba/shares/jellyfin type ext4 (rw,relatime,errors=remount-ro)
```

**Comment by dirks** [comment]
Just spend some time on this as well. In my test case the changed state only occurs, when a second bind mount point is below the first, e.g.:

```yaml
# converge.yml
---
- name: Converge
  hosts: all
  become: true
  vars:
    srcs:
      - /var/lib/mydir
      - /var/lib/myreadonlydir
    dests:
      - /mnt/mydir
      - /mnt/mydir/readonlydir

  tasks:
    - name: Create dummy dirs to bind mount from
      ansible.builtin.file:
        state: directory
        path: '{{ item }}'
        mode: u=rwx,g=rx,o=rx
        owner: root
        group: root
      loop: '{{ srcs }}'

    - name: Mount mydir.
      ansible.posix.mount:
        src: '{{ srcs[0] }}'
        path: '{{ dests[0] }}'
        fstype: none
        opts: bind
        state: mounted

    - name: Mount readonlydir.
      ansible.posix.mount:
        src: '{{ srcs[1] }}'
        path: '{{ dests[1] }}'
        fstype: none
        opts: bind,ro
        state: mounted
```

Definition of test platform:

```yaml
# molecule.yml
---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: mounts-debian12
    box: debian/bookworm64
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
...
```
