### ISSUE TITLE
Ansible Synchronize module fails to connect

### ISSUE THREAD

**Issue by leomoon** [ansible-collections/ansible.posix#474]
##### SUMMARY

If we are re-assigning a variable like password, it will not be evaluated properly with Synchronize.

My setup is like this. Ansible will get the value of `{{ ansible_pass }}` from `secrets.yaml` and assigns it to all these variables in `host_vars/testserver.yaml`:
```yaml
ansible_password: "{{ ansible_pass }}"
ansible_ssh_pass: "{{ ansible_pass }}"
ansible_sudo_pass: "{{ ansible_pass }}"
ansible_become_pass: "{{ ansible_pass }}"
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Synchronize

##### ANSIBLE VERSION
```console
$ ansible --version
ansible [core 2.14.1]
  python version = 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION
```console
$ ansible-galaxy collection list community.general

# /home/USERNAME/.local/lib/python3.10/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 6.1.0  

# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 1.3.6
```

##### CONFIGURATION
```console
CONFIG_FILE() = /home/USERNAME/ansible/ansible.cfg
DEFAULT_ASK_PASS(/home/USERNAME/ansible/ansible.cfg) = False
DEFAULT_ASK_VAULT_PASS(/home/USERNAME/ansible/ansible.cfg) = True
DEFAULT_FILTER_PLUGIN_PATH(/home/USERNAME/ansible/ansible.cfg) = ['/home/USERNAME/ansible/filter_plugins']
DEFAULT_FORCE_HANDLERS(/home/USERNAME/ansible/ansible.cfg) = True
DEFAULT_HOST_LIST(/home/USERNAME/ansible/ansible.cfg) = ['/home/USERNAME/ansible/hosts.yaml']
DEFAULT_REMOTE_USER(/home/USERNAME/ansible/ansible.cfg) = root
DEFAULT_ROLES_PATH(/home/USERNAME/ansible/ansible.cfg) = ['/home/USERNAME/ansible/contrib']
DEFAULT_STRATEGY_PLUGIN_PATH(/home/USERNAME/ansible/ansible.cfg) = ['/home/USERNAME/ansible/mitogen-0.2.9/ansible_mitogen/plugins/strategy']
DEFAULT_TEST_PLUGIN_PATH(/home/USERNAME/ansible/ansible.cfg) = ['/home/USERNAME/ansible/test_plugins']
DEFAULT_TIMEOUT(/home/USERNAME/ansible/ansible.cfg) = 60
DIFF_ALWAYS(/home/USERNAME/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/home/USERNAME/ansible/ansible.cfg) = False
MAX_FILE_SIZE_FOR_DIFF(/home/USERNAME/ansible/ansible.cfg) = 1048576
PERSISTENT_COMMAND_TIMEOUT(/home/USERNAME/ansible/ansible.cfg) = 300
```

##### OS / ENVIRONMENT

```console
$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
```

##### STEPS TO REPRODUCE

If we are re-assigning a variable like password, it will not be evaluated properly with Synchronize.

My setup is like this. Ansible will get the value of `{{ ansible_pass }}` from `secrets.yaml` and assigns it to all these variables in `host_vars/testserver.yaml`:
```yaml
ansible_password: "{{ ansible_pass }}"
ansible_ssh_pass: "{{ ansible_pass }}"
ansible_sudo_pass: "{{ ansible_pass }}"
ansible_become_pass: "{{ ansible_pass }}"
```

Structure of the test case:
```
ansible/
    host_vars/
        testserver.yaml
    secrets.yaml
    sync_test.yaml
```

Contents of host_vars/testserver.yaml
```yaml
---
ansible_host: x.x.x.x
ansible_connection: ssh
ansible_port: 22
ansible_ssh_user: ansible
ansible_become: true
ansible_become_user: root
ansible_password: "{{ ansible_pass }}"
ansible_ssh_pass: "{{ ansible_pass }}"
ansible_sudo_pass: "{{ ansible_pass }}"
ansible_become_pass: "{{ ansible_pass }}"
hostname: "{{ inventory_hostname }}"
```

Contents of secrets.yaml
This has the ssh password here and it is encrypted. But for our test we can leave it not encrypted.
```yaml
ansible_pass: PASSWORDHERE
```

Contents of sync_test.yaml
```yaml
---
- hosts: all
  gather_facts: true
  vars_files:
    - secrets.yaml
  tasks:

  - debug: msg="{{ ansible_pass }} {{ ansible_password }} {{ ansible_ssh_pass }} {{ ansible_sudo_pass }} {{ ansible_become_pass }}"

  - name: create a file (works)
    copy:
      dest: "/tmp/blah"
      content: |
        line 01
        line 02

  - name: copy app-scraper (fails!)
    synchronize:
      src: flask/files/var/opt/app-scraper
      dest: /tmp/
      rsync_opts:
        - "--exclude=.git"
        - "--exclude=__pycache__"
```

##### EXPECTED RESULTS

Excpect Synchronize to also pass/work.
```console
$ ansible-playbook sync_test.yaml -l testserver
Vault password: 

PLAY [all] ******************************************************************

TASK [Gathering Facts] ******************************************************
ok: [testserver]

TASK [debug] ****************************************************************
ok: [testserver] => {
    "msg": "PASSWORDHERE PASSWORDHERE PASSWORDHERE PASSWORDHERE PASSWORDHERE"
}

TASK [create a file (works)] ************************************************
ok: [testserver]

TASK [copy app-scraper ] ********************************************
ok: [testserver]

PLAY RECAP ******************************************************************
testserver                  : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

##### ACTUAL RESULTS

And if you run this you can see the debug message is shwoing the correct password and `create a file` also passes, but it will fail at **synchronize**.
```console
$ ansible-playbook sync_test.yaml -l testserver
Vault password: 

PLAY [all] ******************************************************************

TASK [Gathering Facts] ******************************************************
ok: [testserver]

TASK [debug] ****************************************************************
ok: [testserver] => {
    "msg": "PASSWORDHERE PASSWORDHERE PASSWORDHERE PASSWORDHERE PASSWORDHERE"
}

TASK [create a file (works)] ************************************************
ok: [testserver]

TASK [copy app-scraper (fails!)] ********************************************
fatal: [testserver]: FAILED! => {"changed": false, "cmd": "sshpass -d3 /usr/bin/rsync --delay-updates -F --compress --archive --rsh='/usr/bin/ssh -S none -o Port=22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' --rsync-path='sudo -u root rsync' --exclude=.git --exclude=__pycache__ --out-format='<<CHANGED>>%i %n%L' /home/leomoon/ansible/flask/files/var/opt/app-scraper ansible@x.x.x.x:/tmp/", "msg": "Warning: Permanently added 'x.x.x.x' (ED25519) to the list of known hosts.\r\nPermission denied, please try again.\r\nPermission denied, please try again.\r\nansible@x.x.x.x: Permission denied (publickey,password).\r\nrsync error: unexplained error (code 255) at rsync.c(713) [sender=3.2.7]\n", "rc": 5}

PLAY RECAP ******************************************************************
testserver                  : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

##### TEMPORARY FIX
Ansible is not evaluating the variable properly before passing it to Synchronize and this is a bug but the temporary fix is to **set_fact** those variables before running **Synchronize**!

So the sync_test.yaml should be changed to this:
```yaml
---
- hosts: all
  gather_facts: true
  vars_files:
    - secrets.yaml
  tasks:

  - debug: msg="{{ ansible_pass }} {{ ansible_password }} {{ ansible_ssh_pass }} {{ ansible_sudo_pass }} {{ ansible_become_pass }}"

  - name: create a file (works)
    copy:
      dest: "/tmp/blah"
      content: |
        line 01
        line 02

  - name: temp fix for synchronize to force evaluate variables!
    set_fact:
      ansible_password: "{{ ansible_pass }}"
      ansible_ssh_pass: "{{ ansible_pass }}"
      ansible_sudo_pass: "{{ ansible_pass }}"
      ansible_become_pass: "{{ ansible_pass }}"

  - name: rsync app-scraper (fixed!)
    synchronize:
      src: flask/files/var/opt/app-scraper
      dest: /tmp/
      rsync_opts:
        - "--exclude=.git"
        - "--exclude=__pycache__"
```

And this will work!
