### ISSUE TITLE
Can't create a firewalld zone and set the target in one step

### ISSUE THREAD

**Issue by rsguhr** [ansible-collections/ansible.posix#481]
##### SUMMARY

You can't create a new zone and set the target for this zone in the same run.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

firewalld

##### ANSIBLE VERSION

```paste below
ansible --version
ansible [core 2.15.1]

ansible==8.1.0
```

##### COLLECTION VERSION

```paste below
ansible-galaxy collection list                                           

# /home/rguhr/.local/lib/python3.11/site-packages/ansible_collections
Collection                    Version
----------------------------- -------
[...]
ansible.posix                 1.5.4 
[...]
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /home/rguhr/.ansible.cfg
DEFAULT_CALLBACK_PLUGIN_PATH(/home/rguhr/.ansible.cfg) = ['/home/rguhr/git/github/ansible_stdout_compact_logger']
DEFAULT_FORKS(/home/rguhr/.ansible.cfg) = 10
DEFAULT_STDOUT_CALLBACK(/home/rguhr/.ansible.cfg) = anstomlog
EDITOR(env: EDITOR) = /usr/bin/vim
INTERPRETER_PYTHON(/home/rguhr/.ansible.cfg) = auto_legacy_silent
MAX_FILE_SIZE_FOR_DIFF(/home/rguhr/.ansible.cfg) = 99999999
PAGER(env: PAGER) = less
RETRY_FILES_ENABLED(/home/rguhr/.ansible.cfg) = False
```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  gather_facts: false
  become: true
  vars:
    firewalld_zones:
      - zone: test
        target: "DROP"

  tasks:
    - name: Create/Delete firewalld zones
      ansible.posix.firewalld:
        state: "{{ item.state | default('present') }}"
        target: "{{ item.target | default(omit) }}"
        permanent: true
        zone: "{{ item.zone | default(omit) }}"
      loop: "{{ firewalld_zones }}"
```

##### EXPECTED RESULTS

Zone will be created with correct target in one step

##### ACTUAL RESULTS

```paste below
localhost | FAILED | 480ms
{
  - msg: One or more items failed
  - results: [ {
    - msg: ERROR: Exception caught: org.fedoraproject.FirewallD1.Exception: INVALID_ZONE: test
    - failed: True
    - changed: False
    - item: {
      - zone: test
      - target: DROP
    }
    - ansible_loop_var: item
  } ]
  - changed: False
}
```

##### WORKAROUNDS
```
  vars:
    firewalld_zones:
      - zone: test
      - zone: test
        target: "DROP"
```
