### ISSUE TITLE
firewalld port_forward creates multiple entries with the same port/proto pair

### ISSUE THREAD

**Issue by opoplawski** [ansible-collections/ansible.posix#489]
##### SUMMARY
I set a port forward with:
```
 -  ansible.posix.firewalld:
      port_forward:
        - port: 514
          proto: udp
          toaddr: "{{ lookup('dig', logserver) }}"
          toport: 514
      immediate: yes
      permanent: yes
      state: enabled
```
If the IP address for logserver changes, I end up with multiple port forward entries:
```
# sudo firewall-cmd --list-forward-ports
port=514:proto=udp:toport=514:toaddr=10.10.X.X
port=514:proto=udp:toport=514:toaddr=10.10.Y.Y
```
which isn't what I want and doesn't work.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
firewalld

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.2]
  config file = /export/home/USER/ansible-boulder/ansible.cfg
  configured module search path = ['/export/home/USER/ansible-boulder/library']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /export/home/USER/ansible-boulder:/export/home/USER/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Jun 22 2023, 06:07:18) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection    Version
------------- -------
ansible.posix 1.5.4
```

##### CONFIGURATION

```paste below
CALLBACKS_ENABLED(/export/home/USER/ansible-boulder/ansible.cfg) = ['profile_tasks']
COLLECTIONS_PATHS(/export/home/USER/ansible-boulder/ansible.cfg) = ['/export/home/USER/ansible-boulder', '/export/home/USER/.ansible/collections', '/usr/share/ansible/collections']
CONFIG_FILE() = /export/home/USER/ansible-boulder/ansible.cfg
DEFAULT_FORKS(/export/home/USER/ansible-boulder/ansible.cfg) = 25
DEFAULT_GATHERING(/export/home/USER/ansible-boulder/ansible.cfg) = smart
DEFAULT_HOST_LIST(/export/home/USER/ansible-boulder/ansible.cfg) = ['/export/home/USER/ansible-boulder/inventory']
DEFAULT_INVENTORY_PLUGIN_PATH(/export/home/USER/ansible-boulder/ansible.cfg) = ['/export/home/USER/ansible-boulder/plugins/inventory']
DEFAULT_JINJA2_EXTENSIONS(/export/home/USER/ansible-boulder/ansible.cfg) = jinja2.ext.do
DEFAULT_LOOKUP_PLUGIN_PATH(/export/home/USER/ansible-boulder/ansible.cfg) = ['/export/home/USER/ansible-boulder/plugins/lookup']
DEFAULT_MODULE_PATH(/export/home/USER/ansible-boulder/ansible.cfg) = ['/export/home/USER/ansible-boulder/library']
DEFAULT_ROLES_PATH(/export/home/USER/ansible-boulder/ansible.cfg) = ['/export/home/USER/ansible-boulder/roles']
DEFAULT_STRATEGY(/export/home/USER/ansible-boulder/ansible.cfg) = mitogen_linear
DEFAULT_STRATEGY_PLUGIN_PATH(/export/home/USER/ansible-boulder/ansible.cfg) = ['/export/home/USER/ansible-boulder/mitogen-master/ansible_mitogen/plugins/strategy']
DEFAULT_TEST_PLUGIN_PATH(/export/home/USER/ansible-boulder/ansible.cfg) = ['/export/home/USER/ansible-boulder/plugins/test']
DEFAULT_TIMEOUT(/export/home/USER/ansible-boulder/ansible.cfg) = 40
INJECT_FACTS_AS_VARS(/export/home/USER/ansible-boulder/ansible.cfg) = True
INVENTORY_ENABLED(/export/home/USER/ansible-boulder/ansible.cfg) = ['cobbler', 'ini']
```

##### OS / ENVIRONMENT

controller and target are EL8

##### STEPS TO REPRODUCE

```yaml
 -  ansible.posix.firewalld:
      port_forward:
        - port: 514
          proto: udp
          toaddr: 10.10.10.10
          toport: 514
      immediate: yes
      permanent: yes
      state: enabled
 -  ansible.posix.firewalld:
      port_forward:
        - port: 514
          proto: udp
          toaddr: 10.10.20.20
          toport: 514
      immediate: yes
      permanent: yes
      state: enabled
```
```
# sudo firewall-cmd --list-forward-ports
```

##### EXPECTED RESULTS
```
port=514:proto=udp:toport=514:toaddr=10.10.20.20
```

##### ACTUAL RESULTS

```paste below
port=514:proto=udp:toport=514:toaddr=10.10.10.10
port=514:proto=udp:toport=514:toaddr=10.10.20.20
```
