### ISSUE TITLE
synchronize can't find ssh key on relative path when ansible can

### ISSUE THREAD

**Issue by ltalirz** [ansible-collections/ansible.posix#500]
##### SUMMARY
When providing a relative path to ssh key, synchronize can't find it.

More precisely, this problem occurs when the ansible playbook is not in the directory where ansible is run from. In that case, other ansible tasks find the ssh key just fine, but synchronize does not.

Related (fixed) bug from 2017 https://github.com/ansible/ansible-modules-core/issues/18

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible.posix.synchronize

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.8]
  config file = /home/hpcadmin/pilgrim/ansible.cfg
  configured module search path = ['/home/hpcadmin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/hpcadmin/pilgrim/miniconda/lib/python3.11/site-packages/ansible
  ansible collection location = /home/hpcadmin/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/hpcadmin/pilgrim/miniconda/bin/ansible
  python version = 3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0] (/home/hpcadmin/pilgrim/miniconda/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/hpcadmin/.ansible/collections/ansible_collections
Collection    Version
------------- -------
ansible.posix 1.5.4
```

##### CONFIGURATION

```paste below
CALLBACKS_ENABLED(/home/hpcadmin/pilgrim/ansible.cfg) = ['profile_roles']
CONFIG_FILE() = /home/hpcadmin/pilgrim/ansible.cfg
DEFAULT_FORKS(/home/hpcadmin/pilgrim/ansible.cfg) = 128
DEFAULT_LOG_PATH(/home/hpcadmin/pilgrim/ansible.cfg) = /home/hpcadmin/pilgrim/ansible.log
DEFAULT_ROLES_PATH(/home/hpcadmin/pilgrim/ansible.cfg) = ['/home/hpcadmin/pilgrim/playbooks/roles']
DEFAULT_STDOUT_CALLBACK(/home/hpcadmin/pilgrim/ansible.cfg) = debug
DEFAULT_TIMEOUT(/home/hpcadmin/pilgrim/ansible.cfg) = 30
HOST_KEY_CHECKING(/home/hpcadmin/pilgrim/ansible.cfg) = False
```

##### OS / ENVIRONMENT

CentOS 7.9

##### STEPS TO REPRODUCE

Directory layout
```
id_rsa
ansible.cfg
hosts
playbooks/
  playbook.yml
  folder_to_synchronize/
```

With playbook.yml
```yml
---
- hosts: myhost
  tasks:
  - name: Copy application files
    synchronize:
      src: './folder_to_synchronize'
      dest: /tmp/folder
```

hosts
```yaml
all:
  hosts:
    myhost:
      ansible_host: <IP>
  vars:
    ansible_ssh_private_key_file: id_rsa
    # Replacing this with line below fixes the playbook
    #ansible_ssh_private_key_file: "{{'id_rsa'| realpath }}"
```

ansible.cfg
```
[defaults]
inventory=hosts
```

##### EXPECTED RESULTS

synchronize finds ssh key `id_rsa`

##### ACTUAL RESULTS

ansible finds ssh key `id_rsa`
```
TASK [Gathering Facts] ****************************************************************************************************************************
ok: [ondemand]
```
but `synchronize` fails with
```
TASK [Copy application files] *********************************************************************************************************************
fatal: [ondemand]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh='/usr/bin/ssh -S none -i id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' --out-format='<<CHANGED>>%i %n%L' /home/hpcadmin/synchronize_issue/playbooks/folder hpcadmin@10.132.1.9:/tmp/folder", "msg": "Warning: Identity file id_rsa not accessible: No such file or directory.\nWarning: Permanently added '10.132.1.9' (ECDSA) to the list of known hosts.\r\nhpcadmin@10.132.1.9: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(235) [sender=3.1.3]\n", "rc": 255}
```

**Comment by ltalirz** [comment]
Somewhat related to this: While the above behavior demonstrates that `synchronize` uses the `ansible_ssh_private_key_file` variable [1], it seems to entirely ignore the `ansible_ssh_common_args` variable.

This variable can contain important settings that are required for connecting to the host (e.g. `ProxyJump`s), so it is very unexpected that this variable is ignored. Happy to open another bug for this.


[1] By the way, where does this happen? I looked through the [`synchronize` module source code](https://github.com/ansible-collections/ansible.posix/blob/542643e7860c549a241c9a763d85cbe585f0d54c/plugins/modules/synchronize.py) and did not see it.

**Comment by funkyfuture** [comment]
similarly, when using ssh arguments implied by `use_ssh_args` option the relative path to an identity file isn't resolved, see [this](https://github.com/ansible/ansible/issues/68464) previous report.

it would be helpful when an experienced Ansible developer could give advice where the expansion to an absolute path should happen. within the plugin or when options are read or somewher in between?

**Comment by NotSirius-A** [comment]
I've also encountered the same problem. 

I've skimmed through the code, the issue seems to be that the `rsync` command is run from the directory of the playbook, therefore the **path of the ssh key is relative to the playbook**, not the current working dir or `inventory.yml`.

### Fix?

Consider this line https://github.com/ansible-collections/ansible.posix/blob/692b906b8219c904c489f4cf9fdb6b2a5aff4039/plugins/modules/synchronize.py#L622

Maybe it would be a good idea to just include the `cwd` argument in `run_command` to change the working dir to the same of that from which `ansible-playbook` command is run?

## Workaround
You can use the `private_key` argument with the path to the ssh key **relative to the playbook**.

### My example:

`inventory.yml`
```yml
myhost:
  hosts:
   myhost01:
      ansible_host: hostname
      ansible_user: user
      ansible_become: true
      # Notice the ./ prefix
      ansible_ssh_private_key_file: ./.ssh/key
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
```
The playbook is in a folder 1 level deeper than the inventory, therefore the synchronize argument should be:

```yml
  - name: Synchronize files to remote
    ansible.posix.synchronize:
      src: ./my_files
      dest: "{{ APP_DIR }}"
      recursive: yes
      # It works with the ../ prefix
      private_key: "../.ssh/key"
```
