### ISSUE TITLE
sysctl --system

### ISSUE THREAD

**Issue by drbree82** [ansible-collections/ansible.posix#512]
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ansible.posix.sysctl
##### ADDITIONAL INFORMATION

running a shell command of 
```
sysctl --system
```
can't be called using the module. Currently the only way to reload sysctl is to run 
```
reload: yes
```
against every sysctl module.
Being able to do a general reload would be preferable to having to run shell or cmd calls.

```yaml
- name: Reload sysctl config
  ansible.posix.sysctl:
    state: present
    reload: yes

```
