### ISSUE TITLE
Synchronize module doesn`t work as expected

### ISSUE THREAD

**Issue by LLIycTpbIu** [ansible-collections/ansible.posix#561]
##### SUMMARY

I`m trying to play that:
```
    - name: copy images
      synchronize:
        mode: pull
        src: rsync://*SOME_IP*/var/lib/libvirt/images/
        dest: /var/lib/libvirt/images/
```
and getting that kind of error:
```
"msg": "rsync: [Receiver] failed to connect to 10.47.252.70 (10.47.252.70): Connection timed out (110)\nrsync error: error in socket IO (code 10) at clientserver.c(139) [Receiver=3.2.7]\n"
```
![image](https://github.com/user-attachments/assets/62ce47d7-e4de-47da-aa12-466c947a4950)

btw, when I copy/paste command to terminal, it works fine
`rsync --delay-updates -F --compress --archive --out-format='<<CHANGED>>%i %n%L' rsync://10.47.252.70/var/lib/libvirt/images/ /var/lib/libvirt/images/`

##### ANSIBLE VERSION

```2.16.10```

##### COLLECTION VERSION

```ansible.posix                            1.5.4```

##### EXPECTED RESULTS

It works

##### ACTUAL RESULTS

It fails with error:
