### ISSUE TITLE
Addressing Limitations in Mount Options Retrieval with Proposed ansible.posix.mount_read Module

### ISSUE THREAD

**Issue by jangel97** [ansible-collections/ansible.posix#564]
While using the `ansible.posix.mount` module and `ansible_mounts` facts gathering, I noticed that it's not feasible to extract mount options for specific filesystems, such as `/dev/shm` on RHEL hosts. This issue might also affect other distributions. This limitation hampers the ability to dynamically assess and adjust the configuration of mounted filesystems via Ansible playbooks. In my scenario, for instance, ensuring that `/dev/shm` is mounted with the `noexec` flag is crucial for compliance.

To avoid resorting to the `command` or `shell` modules to run `findmnt` and parse its output, I would advocate for a more integrated solution, a new module that could reliably read the current mounts and their flags directly during runtime.

I propose introducing `ansible.posix.mount_read`, a new module designed to enhance our capabilities with the following features:
- **Read Mount Information**: Capable of querying and returning detailed information about all mounted systems or specific mount points.
- **Filter Options**: Provides the functionality to filter outputs based on particular mount points or options.
- **Compatibility**: Ensures full compatibility with all Unix-like operating systems supported by the `ansible.posix` collection.

I believe this proposal could resonate well with the community and among the maintainers. If so, I am prepared to contribute a Pull Request. However, I would first like to open this for discussion to gauge its viability.

Thank you!

**Comment by jangel97** [comment]
An example of how the proposed module would work in an ansible playbook:
```yaml
- name: Verify Mount Options on Hosts
  hosts: all
  tasks:
    - name: Read specific mount information
      ansible.posix.mount_read:
        path: "/dev/shm"
      register: shm_mount_info

    - name: Check if 'noexec' is present in mount options
      assert:
        that:
          - "'noexec' in shm_mount_info.mount_options"
        fail_msg: "'noexec' flag is not set on /dev/shm"
        success_msg: "'noexec' flag is set on /dev/shm"

    - name: Display all mounts information
      ansible.posix.mount_read:
        filter: "all" 
      register: all_mounts_info

    - name: Debug output for all mounts
      debug:
        msg: "{{ all_mounts_info }}"
```

This example highlights how the module can be effectively used for both specific and general mount configuration checks. Eliminating the need for external scripts or commands.
