### ISSUE TITLE
ansible.posix v 1.6.0 new forward option has wrong type

### ISSUE THREAD

**Issue by alice-rc** [ansible-collections/ansible.posix#582]
##### SUMMARY
Documentation in ansible/posix/plugins/modules/firewalld.py is incorrect
```
    forward:
    description:
      - The forward setting you would like to enable/disable to/from zones within firewalld.
      - This option only is supported by firewalld v0.9.0 or later.
    type: str
```
Should be
```
    forward:
    description:
      - The forward setting you would like to enable/disable to/from zones within firewalld.
      - This option only is supported by firewalld v0.9.0 or later.
    type: bool
```

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
ansible.posix.firewalld

##### ANSIBLE VERSION
ansible.posix          1.6.0
