### ISSUE TITLE
If a comment is appended to a fstab entry state present creates a double-entry .

### ISSUE THREAD

**Issue by vbotka** [ansible-collections/ansible.posix#595]
##### SUMMARY

Given the /tmp/fstab for testing

```bash
shell> cat /tmp/fstab 
/dev/sda /mnt3 ntfs3 defaults 0 0 # mount sda to /mnt3
```

the module ansible.posix.mount

```yaml
    - ansible.posix.mount:
        fstab: /tmp/fstab
        src: /dev/sda
        path: /mnt3
        fstype: ntfs3
        state: present
```

creates a double-entry

```bash
shell> cat /tmp/fstab 
/dev/sda /mnt3 ntfs3 defaults 0 0 # mount sda to /mnt3
/dev/sda /mnt3 ntfs3 defaults 0 0
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible.posix.mount

##### ANSIBLE VERSION

```ini
shell> ansible --version
ansible [core 2.18.0]
  config file = /export/scratch/sandbox/tmp1/test-101/ansible.cfg
  configured module search path = ['/home/vlado/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vlado/env/lib/python3.12/site-packages/ansible
  ansible collection location = /home/vlado/env/lib/python3.12/site-packages/ansible_collections
  executable location = /home/vlado/env/bin/ansible
  python version = 3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0] (/home/vlado/env/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION

```bash
shell> ansible-galaxy collection list ansible.posix

# /home/vlado/env/lib/python3.12/site-packages/ansible_collections
Collection    Version
------------- -------
ansible.posix 1.6.2
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/export/scratch/sandbox/tmp1/test-101/ansible.cfg) = True
CONFIG_FILE() = /export/scratch/sandbox/tmp1/test-101/ansible.cfg
DEFAULT_GATHERING(/export/scratch/sandbox/tmp1/test-101/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/export/scratch/sandbox/tmp1/test-101/ansible.cfg) = ['/scratch/sandbox/tmp1/test-101/hosts']
DEFAULT_ROLES_PATH(/export/scratch/sandbox/tmp1/test-101/ansible.cfg) = ['/scratch/sandbox/tmp1/test-101/roles']
DEFAULT_STDOUT_CALLBACK(/export/scratch/sandbox/tmp1/test-101/ansible.cfg) = yaml
EDITOR(env: EDITOR) = emacs
PAGER(env: PAGER) = /usr/bin/most -s

GALAXY_SERVERS:
```

##### OS / ENVIRONMENT

```ini
shell> cat /etc/os-release 
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

##### STEPS TO REPRODUCE

Create /tmp/fstab for testing

```bash
shell> cat /tmp/fstab 
/dev/sda /mnt3 ntfs3 defaults 0 0 # mount sda to /mnt3
```

Run the play

```yaml
shell> cat pb.yml 
- hosts: localhost

  tasks:

    - ansible.posix.mount:
        fstab: /tmp/fstab
        src: /dev/sda
        path: /mnt3
        fstype: ntfs3
        state: present
```

##### EXPECTED RESULTS

The task should be idempotent. This means, nothing will be changed because the entry in fstab is present

```bash
shell> cat /tmp/fstab 
/dev/sda /mnt3 ntfs3 defaults 0 0 # mount sda to /mnt3
```

##### ACTUAL RESULTS

A double entry is created

```bash
shell> cat /tmp/fstab 
/dev/sda /mnt3 ntfs3 defaults 0 0 # mount sda to /mnt3
/dev/sda /mnt3 ntfs3 defaults 0 0
```
