### ISSUE TITLE
Nothing happened in ansible.posix.synchronize when try to sync from server to server

### ISSUE THREAD

**Issue by mihalt** [ansible-collections/ansible.posix#602]
Hi! I use this 

```
- name: Migrate volumes to new server
  hosts: new_server
  become: true
  tags: migrate
  user: user
  tasks: 
    - name: Copy backup files to server for restore
      ansible.posix.synchronize:
        src: "{{ balancer_certificates_path }}"
        dest: "{{ balancer_certificates_path }}"
        private_key: "{{ private_key_file }}"
        recursive: true
        mode: push
        verify_host: true

      delegate_to: "{{ groups['remote_entrypoint'][0] }}"
```
 
but in the end nothing just happens for me until I press ctrl+c.
-vvv ends something like this

```
<remote.entrypoint.ip> SSH: EXEC ssh -vvvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=
gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="user"' -o ConnectTimeout=10 -o 'ControlPath="/home/user/.ansible/cp/e0d6864a44"' -tt remote.entrypoint.ip '/bin/sh -c '"'"'sudo -H -S -n  -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-rfocmveoyaneifemkeddzjqzckeletko ; /usr/bin/python3.12 /home/user/.ansible/tmp/ansible-tmp-1733403182.7363403-4762-47638893333561/AnsiballZ_synchronize.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
```

From what was suspicious before, I found this in this task
```
<new.server.ip> Python interpreter discovery fallback (unsupported Linux distribution: ubuntu)
Using module file /usr/lib/python3/dist-packages/ansible_collections/ansible/posix/plugins/modules/synchronize.py
```

Can you say me what problem can be here?

**Comment by mihalt** [comment]
After 5 days of debug I found solution. 

I found that rsync works fine on my server if I send it manually from a custom linux user terminal session. It was the same command like this on ansible (but from ansible it wasn't worked):
```
- shell: "rsync /home/user/nginx.conf user@new.server.ip:/home/user/nginx.conf"
```

When I started ssh session from root on a server-sender I found the problem:
```
$ sudo su
$ rsync /home/user/nginx.conf user@new.server.ip:/home/user/nginx.conf
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0644 for '/root/.ssh/id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "/root/.ssh/id_rsa": bad permissions
```

So, looks like that Ansible tries to use ssh key from `/root/.ssh/id_rsa` and runs from a root even if I manually defined `user: user`. And maybe I copied this file from sftp as my custom user, or something like that made too open permissions. So, the command fully resolved my problem:
```
chmod 600 /root/.ssh/id_rsa
```

And a minimalistic play looks like
```
- name: Migrate volumes to new server
  hosts: new_server
  user: user # HIGHLY IMPORTANT TO DEFINE IT HERE TOO. IF THERE ISN'T, THAN ERROR PERSISTS. 
  tasks: 
    - name: Copy backup files to server for restore
      ansible.posix.synchronize:
        src: "{{ balancer_certificates_path }}"
        dest: "{{ balancer_certificates_path }}"

      delegate_to: "{{ groups['remote_entrypoint'][0] }}"
```

And don't forget, that folder to which you copy files should already exist.
