### ISSUE TITLE
firewalld: port_forward expects a list but does not handle multiple parameters

### ISSUE THREAD

**Issue by sents** [ansible-collections/ansible.posix#608]
##### SUMMARY

The port_forward parameter of the firewalld module expects a list of exactly one dictionary argument.
This is unintuitive and confusing behaviour. If the module supports just one argument it should take
dictionary options. If multiple port_forwards are supported taking a list of forwards would be fine.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`ansible.posix.firewalld` port_forward feature

##### ANSIBLE VERSION

```paste below
ansible [core 2.18.1]
  config file = None
  configured module search path = ['/home/finnks/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /nix/store/977791id8h9flmq3c0dh3w1gzbbz11dk-python3.12-ansible-core-2.18.1/lib/python3.12/site-packages/ansible
  ansible collection location = /home/finnks/.ansible/collections:/usr/share/ansible/collections
  executable location = /nix/store/977791id8h9flmq3c0dh3w1gzbbz11dk-python3.12-ansible-core-2.18.1/bin/ansible
  python version = 3.12.8 (main, Dec  3 2024, 18:42:41) [GCC 14.2.1 20241116] (/nix/store/c9m6yd8fg1flz2j5r4bif1ib5j20a0cy-python3-3.12.8/bin/python3.12)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION

```paste below
ansible.posix                            2.0.0
```

##### STEPS TO REPRODUCE

Try to use the 

```yaml
- name: Set up port forwards
  ansible.posix.firewalld:
    zone: public
    permanent: true
    immediate: true
    state: enabled
    port_forward:
      port: "{{ item.from }}"
      toport: "{{ item.to }}"
      proto: "{{ item.proto }}"
  loop: "{{ mapped_ports }}"
```

##### EXPECTED RESULTS

The modules accepts a simple dictionary, or a list of dictionaries if multiple forwards are possible.

##### ACTUAL RESULTS

The modules accepts a list of a **single** dictionary.
