### ISSUE TITLE
firewalld: Is it possible to pass the service parameter a list of services?

### ISSUE THREAD

**Issue by heuwerk** [ansible-collections/ansible.posix#610]
##### SUMMARY

A list of services can be passed to the ansible.posix.firewalld service parameter.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`ansible.posix.firewalld`

##### ADDITIONAL INFORMATION

With `firewall-cmd`, multiple services can be added at the same time by specifying the `--add-service` parameter multiple times.  
I would like to use this behavior for ansible.posix.firewalld as well, as it reduces the overhead when activating multiple services compared to a loop.

I hardly know anything about the internals of firewalld, but from my naive point of view, a `--add-service` would have to be placed in front of each list item to implement this function.

```yaml
- name: My firewalld Playbook
  hosts: localhost
  tasks:
    - name: Allow multiple firewalld services at once \o/
      services:
        - http
        - https
        - dhcp
        - dns
        - ssh
        - mqtt
        - puppetmaster
       state: enabled
```

**Comment by lvlick** [comment]
You can already do this somewhat: 

```
 ansible.posix.firewalld:
    service: "{{item}}"
    permanent: yes
    state: enabled
  loop:
    - http
    - https
```

**Comment by sprottm** [comment]
I've been looking through some past issues looking for one to grab. For this one, you can run the following:

```yaml
- name: My firewalld Playbook
  hosts: localhost
  tasks:
    - name: Allow multiple firewalld services at once \o/
      become: true
      ansible.posix.firewalld:
        service: "{{ item }}"
        state: enabled
      loop:
        - http
        - https
        - dhcp
        - dns
        - ssh
        - mqtt
        - puppetmaster
```
