### ISSUE TITLE
Module authorized_key user schould not be required

### ISSUE THREAD

**Issue by Sprinterfreak** [ansible-collections/ansible.posix#64]
##### SUMMARY
The argument `user` on authorized_key should not be required

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
module: authorized_key

##### ADDITIONAL INFORMATION
The possibility of disabling permissions handling entirely is required for instance, if we like to implement a whole-system key revocation playbook. In my opinion it is a good reason enabling the module to "lazy" process random authorized_keys files given by a path without mangling the permissions.

Sadly also glob does not work on a remote, hence we allready use a little command hack to find target-files. If we where now able to process random authorized_keys files we could archive the rest without using shell invoking some hacky sed'ing.

Having the authorized_key module available for this would improve security, because implementing a state and valid-key check while iterating over the `__revoked__.pub`-file in sed or lineinfile would break the rules of ansible in terms of "is not a programming language". But we where forced to. Just imagine an excess newline. o.O

```yaml
    - name: authorized_keys
      block:
      - name: Collect all available files
        command: chdir=/ find /root /etc /home /var -type f -name authorized_keys -print
        register: authorized_keys_files

      - name: Delete revoked keys from all users
        authorized_key:
          path: "{{ item }}"
          state: absent
          manage_dir: no
          key: "{{ lookup('file', 'pubkeys/__revoked__.pub') }}"
        with_items:
          - "{{ authorized_keys_files.stdout_lines }}"
```

**Comment by Sprinterfreak** [comment]
A workaround was found

```yaml
    - name: authorized_keys
      block:
      - name: Collect all available users
        command: awk -F':' '{if ($3 > 1000 || $1 == "root" || $1 == "www-data" ) print $1}' /etc/passwd
        register: all_remote_users

      - name: Delete revoked keys
        authorized_key:
          user: "{{ item }}"
          state: absent
          manage_dir: no
          key: "{{ lookup('file', 'pubkeys/__revoked__.pub') }}"
        with_items:
          - "{{ all_remote_users.stdout_lines }}"
```
