### ISSUE TITLE
ansible.posix.firewalld error "forward is not supported parameters" for firewalld >= 0.9.0

### ISSUE THREAD

**Issue by zdudic** [ansible-collections/ansible.posix#641]
##### SUMMARY

The usage of parameter forward fails with err that this parameter is not supported. It's for remote host RHEL 9. 
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
Confirm with ansible-core 2.12 and 2.15
```

##### COLLECTION VERSION

```paste below
ansible.posix                            1.5.4
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

RHEL or OL 9

##### STEPS TO REPRODUCE

```yaml
Task example:
- name: Manage Forward as Disabled
  ansible.posix.firewalld:
    zone: public
    state: disabled
    forward: false
    permanent: true

```

##### EXPECTED RESULTS

I expect to have same result as Linux native command: 
firewall-cmd --remove-forward --permanent

##### ACTUAL RESULTS

```paste below
Error is:

FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible.posix.firewalld) module: forward. Supported parameters include: icmp_block, icmp_block_inversion, immediate, interface, masquerade, offline, permanent, port, port_forward, rich_rule, service, source, state, target, timeout, zone."}

```
