### ISSUE TITLE
firewalld module does not permanently set an interface zone on CentOS / RedHat due to upstream bugs

### ISSUE THREAD

**Issue by StudioMaX** [ansible-collections/ansible.posix#75]
##### SUMMARY

As per [NetworkManager and firewalld - Zone is lost on network restart](https://access.redhat.com/discussions/1455033), this ansible firewalld module is unable to persist zone settings for interfaces. This can be enhanced/compensated for by also running a `nmcli connection modify conn_name connection.zone zone_name` command if the interface is managed by network managed. Unfortunately, the current ansible `nmcli` module does not expose zone settings.
##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

firewalld
##### ANSIBLE VERSION

```paste below
ansible 2.9.11
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Jul 20 2020, 15:37:01) [GCC 7.5.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(ansible.cfg) = True
ANSIBLE_SSH_ARGS(ansible.cfg) = -o ServerAliveInterval=30 -o ControlMaster=auto -o ControlPersist=60s -o PreferredAuthentications=publickey,password,keyboard-interactive
DEFAULT_BECOME_METHOD(ansible.cfg) = sudo
DEFAULT_GATHERING(ansible.cfg) = smart
DEFAULT_HASH_BEHAVIOUR(ansible.cfg) = merge
```

##### OS / ENVIRONMENT

Ubuntu 16.04/18.04 LTS control host, CentOS 7.8 target
##### STEPS TO REPRODUCE

```yaml
    - name: Set zone for the internal network
      become: true
      firewalld:
        permanent: true
        immediate: true
        zone: internal
        interface: eth0
        state: enabled
```

##### EXPECTED RESULTS

The firewall zone was set after rebooting or restarting firewalld
##### ACTUAL RESULTS

The change is forgotten and interface switches back to the default public zone

E.g. after running play

```
# firewall-cmd --zone=internal --list-all
internal
  target: default
  icmp-block-inversion: no
  interfaces: eth0
  ...
```

E.g. after `systemctl restart firewalld`, interfaces empty.

```
# firewall-cmd --zone=internal --list-all
internal
  target: default
  icmp-block-inversion: no
  interfaces: 
...
```

 _Copied from original issue: [ansible/ansible#41738](https://github.com/ansible/ansible/issues/41738)_

**Comment by maxamillion** [comment]
This is a bug in upstream firewalld, bug was previously filed by someone else before this issue was found but I wanted to link it here for posterity.

https://bugzilla.redhat.com/show_bug.cgi?id=1112742

**Comment by Akasurde** [comment]
The above-mentioned bug is resolved. @StudioMaX Do you think we should close this as well? Thanks,

**Comment by StudioMaX** [comment]
To be honest, I don’t know, as I haven’t used this action for a long time. What fixed bug are you talking about? [This one](https://bugzilla.redhat.com/show_bug.cgi?id=1112742)? It was marked as fixed in 2015, but according to the history of this issue, the problem was observed by users in 2020 as well. I think it's better to ask other users from the original issue.

**Comment by phpHavok** [comment]
I can confirm this has happened to me recently (within the past month) on CentOS 8.3 and is still an issue. It's very annoying because you either have to run the module twice or manually push a ZONE= line to the sysconfig script to get around it.

**Comment by Akasurde** [comment]
Before

```
[root@localhost vagrant]# cat /etc/redhat-release
CentOS Linux release 8.3.2011
[root@localhost vagrant]# rpm -qa | grep firewalld
firewalld-filesystem-0.9.3-1.el8.noarch
firewalld-0.9.3-1.el8.noarch
[root@localhost vagrant]# firewall-cmd --zone=internal --list-all
internal
  target: default
  icmp-block-inversion: no
  interfaces:
  sources:
  services: cockpit dhcpv6-client mdns samba-client ssh
  ports:
  protocols:
  forward: no
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
```

Ansible Playbook run
```
TASK [Set zone for the internal network] ******************************************************
task path: /Volumes/data/src/playbooks/posix/firewalld/75.yml:5
redirecting (type: modules) ansible.builtin.firewalld to ansible.posix.firewalld
changed: [127.0.0.1] => {"ansible_facts": {"discovered_interpreter_python": "/usr/libexec/platform-python"}, "changed": true, "msg": "Permanent and Non-Permanent(immediate) operation, Changed eth1 to zone internal"}
META: ran handlers
META: ran handlers
```

```
[root@localhost vagrant]# firewall-cmd --zone=internal --list-all
internal (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth1
  sources:
  services: cockpit dhcpv6-client mdns samba-client ssh
  ports:
  protocols:
  forward: no
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
[root@localhost vagrant]# systemctl restart firewalld
[root@localhost vagrant]# firewall-cmd --zone=internal --list-all
internal (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth1
  sources:
  services: cockpit dhcpv6-client mdns samba-client ssh
  ports:
  protocols:
  forward: no
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
```

I am not able to reproduce this. Any reproduction steps will help.

needs_info
