### ISSUE TITLE
Firewall - after definition of new zone, setting specifics for zone fails

### ISSUE THREAD

**Issue by ArchitectPim** [ansible-collections/ansible.posix#96]
##### SUMMARY

Defining a **new firewall zone** and subsequenially defining the services for this zone results in failure for the definition of the service.  
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

firewalld
##### ANSIBLE VERSION

```paste below
ansible 2.9.13
  config file = /srv/ansible/ansible.cfg
  configured module search path = ['/home/pimaarts/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION

```paste below
[defaults]
collections_paths = ./collections
roles_path = ./roles
inventory = ./inventory/hosts.ini
log_path=./logs/logfile
```

##### OS / ENVIRONMENT

Control host CentOS 8.2 / target CentOS 8.2

The firewall zone used 'newzone' does not exist!
##### STEPS TO REPRODUCE

```yaml
collections:
    - ansible.posix

  tasks:

  - name: Firewall - define the zone
    ansible.posix.firewalld:
      zone: newzone
      state: present
      permanent: yes

  - name: Firewall - set the service for the zone
    ansible.posix.firewalld:
      zone: newzone
      service: ssh
      state: enabled
      permanent: yes
```

##### EXPECTED RESULTS

To be able to define a firewall zone and the specifics of the firewall zone in the same playbook.
When a firewall reload is performed explicitly after the creation of the zone, no failure occurs.

```yaml
collections:
    - ansible.posix

  tasks:

  - name: Firewall - define the zone
    ansible.posix.firewalld:
      zone: newzone
      state: present
      permanent: yes

 - name: Firewall - reload
    command: firewall-cmd --reload

  - name: Firewall - set the service for the zone
    ansible.posix.firewalld:
      zone: newzone
      service: ssh
      state: enabled
      permanent: yes
```

##### ACTUAL RESULTS

```paste below
TASK [Firewall - define the zone (CentOS)] ******************************************************************************************************************************************
changed: [bookstack..studiumnovum.nl]

TASK [Firewall - set the zone (CentOS)] *********************************************************************************************************************************************
fatal: [bookstack.studiumnovum.nl]: FAILED! => {"changed": false, "msg": "ERROR: Exception caught: org.fedoraproject.FirewallD1.Exception: INVALID_ZONE: newzone"}

```

**Comment by maxamillion** [comment]
This doesn't fail on a RHEL 8.2 system, so I find it odd that it's failing on a CentOS 8.2 system.

```
$ ansible-playbook /tmp/testing.yml -i ~/src/dev/ansible-runner/inventory.ini

PLAY [testing ansible.posix.firewalld] **************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************
ok: [rhel8localvm]

TASK [Firewall - define the zone] *******************************************************************************************************
changed: [rhel8localvm]

TASK [Firewall - set the service for the zone] ******************************************************************************************
changed: [rhel8localvm]

PLAY RECAP ******************************************************************************************************************************
rhel8localvm               : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
```
$ cat /tmp/testing.yml
---
- name: testing ansible.posix.firewalld
  hosts: rhel8
  tasks:
    - name: Firewall - define the zone
      ansible.posix.firewalld:
        zone: newzone
        state: present
        permanent: yes

    - name: Firewall - set the service for the zone
      ansible.posix.firewalld:
        zone: newzone
        service: ssh
        state: enabled
        permanent: yes
```

```
$ cat ~/src/dev/ansible-runner/inventory.ini
[rhel8]
rhel8localvm  ansible_host=192.168.122.100 ansible_user=root
```

```
$ ansible rhel8 -m setup -a 'filter=ansible_distribution*' -i ~/src/dev/ansible-runner/inventory.ini
rhel8localvm | SUCCESS => {
    "ansible_facts": {
        "ansible_distribution": "RedHat",
        "ansible_distribution_file_parsed": true,
        "ansible_distribution_file_path": "/etc/redhat-release",
        "ansible_distribution_file_search_string": "Red Hat",
        "ansible_distribution_file_variety": "RedHat",
        "ansible_distribution_major_version": "8",
        "ansible_distribution_release": "Ootpa",
        "ansible_distribution_version": "8.2",
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false
}
```

**Comment by ArchitectPim** [comment]
I have to apologize. I performed a retest and it works.

My original playbook was slightly different from the presented one - I thought it to be a non-essential difference. 
In the _set service task_ I had included _immediate = yes_.  

```
collections:
    - ansible.posix

  tasks:

  - name: Firewall - define the zone
    ansible.posix.firewalld:
      zone: newzone
      state: present
      permanent: yes

  - name: Firewall - set the service for the zone
    ansible.posix.firewalld:
      zone: newzone
      service: ssh
      state: enabled
      permanent: yes
      immediate: yes
```
