### ISSUE TITLE
firewalld_info (new module request)

### ISSUE THREAD

**Issue by ArchitectPim** [ansible-collections/ansible.posix#98]
##### SUMMARY

Defining the end-state of the firewall settings independently of the begin-state of the firewall, so replacing the existing state with the desired end-state (if changed).

Currently with the **firewalld** module, the changes are made incrementally on the existing state.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

firewalld
##### ADDITIONAL INFORMATION

First I have to tell that I am quite new to Ansible. My understanding of Ansible is that is a configuration management system to be used to manage servers from a central point. In my opinion this means that I can define and set the end-state, **independently from the starting state**.

For firewalld this does not work.

When the starting state is (in the example I focus only on the services, but the story holds true for all zone parameters):
```code
$ sudo firewall-cmd --list-services
https
```
Executing the task:

```yaml
  - firewalld:
      zone: somezone
      service: ssh
      permanent: yes
      state: enabled
```
will result in:
```code
$ sudo firewall-cmd --list-services
https ssh
```
I know I can remove a service with a task:
```yaml
  - firewalld:
      zone: somezone
      service: http
      permanent: yes
      state: disabled
```
However to be able to do this, I first need to determine by logging into the server which services are enabled and then add for all not required services a task. I my opinion, this is not how it should work.

A firewall is key in the security of a server. So, in my opinion, it is necessary to be able to define the end-state of a firewall independently of the start-start.
